/** Marathi catalogue, part 11. Keyed by the exact English source. */
export const MR_PART_11: Record<string, string> = {
  'Every active incident across every domain, ranked by severity.':
    'प्रत्येक क्षेत्रातील प्रत्येक सुरू घटना, तीव्रतेनुसार क्रमवार.',
  'Every AI response in this platform is generated by a local, deterministic demonstration provider - no external model endpoint is contacted and no credential material exists in the application bundle. This page governs that capability regardless: the registers, risk assessment and oversight enforcement shown here are the same mechanism that would govern a production model.':
    'या मंचावरील प्रत्येक कृत्रिम बुद्धिमत्ता उत्तर स्थानिक, निश्चित परिणामी प्रात्यक्षिक पुरवठादाराकडून तयार होते - कोणत्याही बाह्य प्रारूप अंतिम बिंदूशी संपर्क होत नाही आणि अनुप्रयोग संचात कोणतीही ओळखपत्रे नाहीत. तरीही हे पान त्या क्षमतेवर नियंत्रण ठेवते: येथे दाखवलेल्या नोंदवह्या, जोखीम मूल्यांकन आणि देखरेख अंमलबजावणी हीच यंत्रणा उत्पादन प्रारूपावरही नियंत्रण ठेवेल.',
  'Every AI-originated recommendation requiring human review, with reviewer and modification notes. Pending items may be reviewed below.':
    'मानवी पुनरावलोकन आवश्यक असलेली प्रत्येक कृत्रिम बुद्धिमत्ता-निर्मित शिफारस, पुनरावलोकनकर्ता व फेरबदल टिपणांसह. प्रलंबित बाबींचे खाली पुनरावलोकन करता येईल.',
  'Every approval, rejection and escalation is written permanently to the audit trail.':
    'प्रत्येक मान्यता, नकार आणि उन्नयन कायमस्वरूपी लेखापरीक्षा मागोव्यात लिहिले जाते.',
  'Every bar carries the same hue deliberately: the residuals are small numbers on a scale built for severity, and colouring them by magnitude would imply a seriousness the arithmetic does not support. Direction is the whole reading.{0}':
    'प्रत्येक पट्टीला जाणीवपूर्वक एकच रंगछटा दिली आहे: शिल्लक फरक हे तीव्रतेसाठी बनवलेल्या प्रमाणावरील लहान आकडे आहेत, आणि त्यांना आकारमानानुसार रंग दिल्यास गणिताला अभिप्रेत नसलेले गांभीर्य सूचित होईल. दिशा हेच संपूर्ण वाचन आहे.{0}',
  'Every change made this session — enabling, pausing, cadence, classification, retention, ownership, syncs, additions and removals — is discarded and the register returns to its seed state.':
    'या सत्रात केलेला प्रत्येक बदल — कार्यान्वित करणे, थांबवणे, वारंवारता, वर्गीकरण, जतन कालावधी, मालकी, समक्रमण, भर आणि वगळणी — रद्द होतो आणि नोंदवही तिच्या मूळ बीज स्थितीत परत येते.',
  'Every coastal segment ranked by modelled vulnerability index.':
    'प्रतिरूपित असुरक्षितता निर्देशांकानुसार क्रमवार लावलेला प्रत्येक किनारी भाग.',
  'Every commitment naming this scope, longest-standing failure first. Each row states the register it came from and the basis on which its standing was derived.':
    'या व्याप्तीचा उल्लेख असलेली प्रत्येक वचनबद्धता, सर्वात जुने अपयश प्रथम. प्रत्येक ओळ ती कोणत्या नोंदवहीतून आली आणि तिची सद्यस्थिती कोणत्या आधारावर काढली हे नमूद करते.',
  'Every commitment on this reading, by standing. {0}.':
    'या वाचनावरील प्रत्येक वचनबद्धता, सद्यस्थितीनुसार. {0}.',
  "Every condition the engine applies, stated in full. An officer, a ratepayer's advocate and an auditor should all be able to read exactly what put a property on the worklist - and the lawful explanations that may mean it should come straight back off again.":
    'प्रणाली लागू करत असलेली प्रत्येक अट, संपूर्णपणे नमूद. एखादी मालमत्ता कार्यसूचीवर कशामुळे आली - आणि ती लगेच पुन्हा वगळावी लागेल असे कायदेशीर स्पष्टीकरण कोणते - हे अधिकारी, करदात्याचा वकील आणि लेखापरीक्षक या सर्वांना नेमके वाचता आले पाहिजे.',
  'Every consequential action - approvals, transitions, exports, denials - is written to an append-style event log with actor, reason and outcome.':
    'प्रत्येक परिणामकारक कृती - मान्यता, संक्रमणे, निर्यात, नकार - कर्ता, कारण आणि निष्कर्षासह केवळ-भर घालता येणाऱ्या घटना नोंदवहीत लिहिली जाते.',
  "Every contract's risk score is the weighted sum of five published indicators: category concentration, repeated extensions, unusual variation magnitude, milestone delivery delay and supplier performance deterioration. Select a contract in the table above to see its breakdown.":
    'प्रत्येक कराराचा जोखीम गुण हा पाच प्रकाशित निर्देशकांची भारित बेरीज असतो: श्रेणी केंद्रीकरण, वारंवार मुदतवाढी, असामान्य फरकाचे आकारमान, टप्पा पूर्ततेतील विलंब आणि पुरवठादार कामगिरीतील घसरण. त्याची विभागणी पाहण्यासाठी वरील तक्त्यात करार निवडा.',
  'Every dataset carries a declared retention period in months - the shortest currently in the register is {0} months. This demonstration environment does not implement automated deletion at the retention boundary: the in-session store described in Evidence &amp; Audit exists for the lifetime of the browser session, not on a retention schedule. A production deployment must implement enforced deletion, not merely a documented retention figure.':
    'प्रत्येक माहितीसंचास महिन्यांत घोषित जतन कालावधी असतो - सध्या नोंदवहीतील सर्वात कमी कालावधी {0} महिने आहे. हे प्रात्यक्षिक वातावरण जतन मर्यादेवर स्वयंचलित विलोपन राबवत नाही: पुरावा &amp; लेखापरीक्षा मध्ये वर्णन केलेला सत्रांतर्गत कोश ब्राउझर सत्राच्या कालावधीपुरता असतो, जतन वेळापत्रकानुसार नाही. उत्पादन तैनातीत केवळ दस्तऐवजीकृत जतन आकडा पुरेसा नाही, तेथे सक्तीचे विलोपन राबवणे आवश्यक आहे.',
  'Every dataset carrying personal data reachable by your principal, with exactly what minimisation is applied. A dataset with no recorded measure is flagged, not hidden.':
    'तुमच्या वापरकर्त्याला उपलब्ध असलेला वैयक्तिक माहिती बाळगणारा प्रत्येक माहितीसंच, आणि त्यावर नेमकी कोणती किमानीकरणाची उपाययोजना लागू आहे. ज्यावर कोणतीही उपाययोजना नोंदलेली नाही असा माहितीसंच लपवला जात नाही, तर चिन्हांकित केला जातो.',
  'Every dataset in the register above is provisioned against a single declared purpose - the institutional reason the corporation is entitled to hold and process it':
    'वरील नोंदवहीतील प्रत्येक माहितीसंच एकाच घोषित प्रयोजनासाठी दिला जातो - तो ठेवण्याचा व त्यावर प्रक्रिया करण्याचा महानगरपालिकेस अधिकार देणारे संस्थात्मक कारण',
  'Every dataset read above passes both the role/attribute permission engine and its own declared allowed-role list and classification ceiling. {0} access polic{1} are additionally registered against data-sensitive resources, including:':
    'वर वाचलेला प्रत्येक माहितीसंच भूमिका/गुणधर्म परवानगी प्रणाली तसेच स्वतःची घोषित अनुमत-भूमिका यादी आणि वर्गीकरण मर्यादा या दोन्हींतून जातो. माहिती-संवेदनशील साधनांविरुद्ध याखेरीज {0} प्रवेश धोरण{1} नोंदवलेली आहेत, त्यांत:',
  'Every declared risk with its controls, owner and review schedule.':
    'प्रत्येक घोषित जोखीम तिच्या नियंत्रणे, जबाबदार अधिकारी आणि पुनरावलोकन वेळापत्रकासह.',
  'Every empanelled contractor holding at least one contract within your authorised scope, ranked by delivery index (lowest first).':
    'तुमच्या प्राधिकृत व्याप्तीत किमान एक करार असलेला प्रत्येक सूचीबद्ध कंत्राटदार, अंमलबजावणी निर्देशांकानुसार क्रमवार (सर्वात कमी प्रथम).',
  'Every facility within your authorised ward scope, with the condition that qualifies it. Availability alone is never reported here.':
    'तुमच्या प्राधिकृत प्रभाग व्याप्तीतील प्रत्येक सुविधा, तिला पात्र ठरवणाऱ्या स्थितीसह. केवळ उपलब्धता येथे कधीही नोंदवली जात नाही.',
  'Every facility within your authorised ward scope, with the ground it has left and the wait a family meets at its gate.':
    'तुमच्या प्राधिकृत प्रभाग व्याप्तीतील प्रत्येक सुविधा, तिच्याकडे शिल्लक असलेली जागा आणि तिच्या दारात कुटुंबाला करावी लागणारी प्रतीक्षा यांसह.',
  'Every feeder circuit within your authorised ward scope.':
    'तुमच्या प्राधिकृत प्रभाग व्याप्तीतील प्रत्येक फीडर मार्गिका.',
  'Every figure above is a claim. The verification tab tests them.':
    'वरील प्रत्येक आकडा हा एक दावा आहे. पडताळणी पट्टी त्यांची चाचणी घेते.',
  'Every figure here describes a settlement and the service it receives - water points, toilet seats, collection rounds, lighting. Nothing describes a resident. There is no household register, no name and no eligibility determination anywhere behind this page, and the service exposes no method that could return one. The recognition status shown is a service-entitlement classification used for planning delivery; it is not a finding about tenure, legality or anyone&apos;s rights.':
    'येथील प्रत्येक आकडा एका वसाहतीचे आणि तिला मिळणाऱ्या सेवेचे वर्णन करतो - पाणी नळ, शौचालय आसने, संकलन फेऱ्या, प्रकाशव्यवस्था. कशाचेही वर्णन रहिवाशाबद्दल नाही. या पानामागे कोठेही कुटुंब नोंदवही, नाव किंवा पात्रता निर्धारण नाही, आणि सेवा असे काहीही परत करू शकणारी कोणतीही पद्धत उघड करत नाही. दाखवलेली मान्यता स्थिती ही सेवा वितरणाच्या नियोजनासाठी वापरली जाणारी सेवा-पात्रता वर्गवारी आहे; ती मालकी हक्क, कायदेशीरपणा किंवा कोणाच्याही हक्कांबाबतचा निष्कर्ष नाही.',
  "Every figure here is derived from the corporation's budget, revenue and project records. Where this page and the financial system of record disagree, the system of record is authoritative. This is an intelligence layer, not a ledger.":
    'येथील प्रत्येक आकडा महानगरपालिकेच्या अर्थसंकल्प, महसूल आणि प्रकल्प नोंदींवरून काढलेला आहे. हे पान आणि अधिकृत वित्तीय प्रणाली यांच्यात मतभेद असल्यास अधिकृत प्रणालीच प्रमाण मानली जाईल. हा बुद्धिमत्ता स्तर आहे, लेखापुस्तक नाही.',
  'Every figure is a ward-and-category aggregate. No trader, premises or licence number appears anywhere behind this page. Naming a licensee would make this an enforcement register answering to a different legal basis; what a management platform should report is how well the regime is administered.':
    'प्रत्येक आकडा हा प्रभाग-व-श्रेणी एकत्रित आकडा आहे. या पानामागे कोठेही व्यापारी, जागा किंवा परवाना क्रमांक दिसत नाही. परवानाधारकाचे नाव दिल्यास ही वेगळ्या कायदेशीर आधारावर चालणारी कारवाई नोंदवही ठरेल; व्यवस्थापन मंचाने ही व्यवस्था किती चांगल्या प्रकारे चालवली जाते हेच नोंदवायचे असते.',
  'Every figure is generated from a fixed seed, so the same principal sees the same city on every visit - no figure moves without cause.':
    'प्रत्येक आकडा ठराविक बीजावरून तयार होतो, त्यामुळे तोच वापरकर्ता प्रत्येक भेटीत तेच शहर पाहतो - कोणताही आकडा विनाकारण बदलत नाही.',
  'Every figure the platform presents can be traced through these nine stages, end to end.':
    'मंच सादर करत असलेल्या प्रत्येक आकड्याचा माग या नऊ टप्प्यांतून, आरंभापासून अखेरपर्यंत काढता येतो.',
  'Every garden, playground and recreation ground within your authorised ward scope.':
    'तुमच्या प्राधिकृत प्रभाग व्याप्तीतील प्रत्येक उद्यान, क्रीडांगण आणि मनोरंजन मैदान.',
  'Every incident in this register is expected to move through these stages. Counts below reflect incidents currently at that stage; connective stages have no discrete status of their own.':
    'या नोंदवहीतील प्रत्येक घटना या टप्प्यांतून जाणे अपेक्षित आहे. खालील संख्या सध्या त्या टप्प्यावर असलेल्या घटना दर्शवतात; जोडणाऱ्या टप्प्यांना स्वतःची स्वतंत्र स्थिती नसते.',
  'Every institutional role, ordered by seniority band then classification ceiling.':
    'प्रत्येक संस्थात्मक भूमिका, ज्येष्ठता पट्ट्यानुसार आणि नंतर वर्गीकरण मर्यादेनुसार क्रमवार.',
  'Every intelligence item, alert and decision traces back through transformation, metric and source with a visual provenance rail.':
    'प्रत्येक बुद्धिमत्ता बाब, इशारा आणि निर्णयाचा माग दृश्य उगम पट्टीद्वारे रूपांतर, मापदंड आणि स्रोतापर्यंत मागे काढता येतो.',
  'Every interment consumes ground that is not returned. A ground that fills does not refill, so a facility reaching capacity is a crisis that arrives without warning and cannot be answered quickly - acquiring land for a burial ground needs a willing seller, a consenting neighbourhood and a community that accepts the site, and the lead time is measured in years. The years-remaining column is therefore a planning instruction, not a statistic. This page holds facilities and capacity only: no interment record, no name and no plot allotment appears anywhere behind it, because the register of the dead belongs to the Registrar and to each ground&apos;s own managing committee.':
    'प्रत्येक दफनासाठी वापरलेली जमीन पुन्हा मिळत नाही. भरलेली दफनभूमी पुन्हा रिकामी होत नाही, त्यामुळे क्षमता संपत आलेली सुविधा हे पूर्वसूचनेशिवाय येणारे आणि लवकर सोडवता न येणारे संकट असते - दफनभूमीसाठी जमीन घ्यायची तर विकण्यास तयार मालक, संमती देणारा परिसर आणि ती जागा स्वीकारणारा समाज लागतो, आणि त्याला लागणारा काळ वर्षांत मोजला जातो. त्यामुळे शिल्लक वर्षांचा स्तंभ ही आकडेवारी नसून नियोजनाची सूचना आहे. या पानावर केवळ सुविधा आणि क्षमता आहे: यामागे कोठेही दफनाची नोंद, नाव किंवा जागेचे वाटप नाही, कारण मृतांची नोंदवही निबंधकाकडे आणि प्रत्येक दफनभूमीच्या स्वतःच्या व्यवस्थापन समितीकडे असते.',
  'Every metric traces to its source record and the computation that produced it. Nothing is asserted without provenance.':
    'प्रत्येक मापदंडाचा माग त्याच्या स्रोत नोंदीपर्यंत आणि तो तयार करणाऱ्या गणनेपर्यंत काढता येतो. उगमाशिवाय काहीही मांडले जात नाही.',
  'Every model in this registry is a demonstration simulation. In this environment, no request ever reaches an external model endpoint - every AI response is produced by the local deterministic provider described in AI Governance. Provider, deployment and version fields describe what a governed production deployment would record, not a live connection.':
    'या नोंदवहीतील प्रत्येक प्रारूप ही प्रात्यक्षिक नक्कल आहे. या वातावरणात कोणतीही विनंती बाह्य प्रारूप अंतिम बिंदूपर्यंत जात नाही - प्रत्येक कृत्रिम बुद्धिमत्ता उत्तर कृत्रिम बुद्धिमत्ता कारभार मध्ये वर्णन केलेल्या स्थानिक निश्चित परिणामी पुरवठादाराकडून तयार होते. पुरवठादार, तैनाती आणि आवृत्ती ही क्षेत्रे नियंत्रित उत्पादन तैनातीत काय नोंदवले जाईल याचे वर्णन करतात, प्रत्यक्ष जोडणीचे नाही.',
  'Every model this platform is capable of invoking, its approved use and its evaluation status.':
    'हा मंच वापरू शकेल असे प्रत्येक प्रारूप, त्याचा मंजूर वापर आणि त्याची मूल्यमापन स्थिती.',
  'Every municipal corporation in Maharashtra this build can be deployed against. Switch the active corporation from the deployment selector in the command bar.':
    'ही आवृत्ती ज्यांवर तैनात करता येते अशा महाराष्ट्रातील प्रत्येक महानगरपालिका. आदेश पट्टीतील तैनाती निवडकातून सक्रिय महानगरपालिका बदला.',
  'Every municipal school within your authorised ward scope.':
    'तुमच्या प्राधिकृत प्रभाग व्याप्तीतील प्रत्येक महानगरपालिका शाळा.',
  'Every other page in this Trust Centre': 'या विश्वास केंद्रातील इतर प्रत्येक पान',
  'Every other screen here reports on the executive wing. A decision case in the Decision Centre ends with an officer - but a great many municipal matters cannot take effect until the Corporation has resolved on them, and expenditure above a committee&apos;s sanction limit rises to the house above it. Without this record the platform would overstate what an officer alone can commit.':
    'येथील इतर प्रत्येक पडदा कार्यकारी शाखेबाबत माहिती देतो. निर्णय केंद्रातील निर्णय प्रकरण अधिकाऱ्यापाशी संपते - परंतु अनेक महानगरपालिका विषय महासभेने ठराव केल्याशिवाय अंमलात येऊ शकत नाहीत, आणि समितीच्या मंजुरी मर्यादेपलीकडचा खर्च वरच्या सभागृहाकडे जातो. या नोंदीशिवाय एकटा अधिकारी काय वचनबद्ध करू शकतो याचे मंचाकडून अतिरंजित चित्र उभे राहिले असते.',
  'Every programme classified against its own target, not a uniform bar.':
    'प्रत्येक कार्यक्रमाचे वर्गीकरण एकसमान मर्यादेवर नव्हे, तर त्याच्या स्वतःच्या लक्ष्याच्या तुलनेत केले जाते.',
  'Every published graph, ordered by how recently its pipeline was validated. Select a row to open its pipeline.':
    'प्रत्येक प्रकाशित आलेख, त्याच्या प्रक्रियामार्गाची पडताळणी किती अलीकडे झाली त्यानुसार क्रमवार. प्रक्रियामार्ग उघडण्यासाठी ओळ निवडा.',
  'Every read and write is scoped to the narrowest role, ward, department and classification that permits it.':
    'प्रत्येक वाचन व लेखन ते ज्यास परवानगी देते अशा सर्वात संकुचित भूमिका, प्रभाग, विभाग आणि वर्गीकरणापुरतेच मर्यादित असते.',
  'Every recommendation cites the record that produced it, traceable end to end.':
    'प्रत्येक शिफारस तिला जन्म देणाऱ्या नोंदीचा संदर्भ देते, जिचा माग आरंभापासून अखेरपर्यंत काढता येतो.',
  'Every record carries a tenant identifier and every service call filters to it before any further check is applied.':
    'प्रत्येक नोंदीस आस्थापना ओळखक्रमांक असतो आणि पुढील कोणतीही तपासणी लागू होण्यापूर्वी प्रत्येक सेवा कॉल त्यानुसार गाळणी करतो.',
  'Every record in the Anomalies section identifies a statistical pattern that requires assessment. Disposition labels - anomaly, unusual pattern, investigation candidate, reconciliation required - describe the pattern only. They are not, and must never be read as, a finding against any person, officer, contractor or organisation.':
    'विसंगती विभागातील प्रत्येक नोंद मूल्यमापन आवश्यक असलेला सांख्यिकीय नमुना दर्शवते. विसंगती, असामान्य नमुना, तपास प्रकरण, ताळमेळ आवश्यक अशी वर्गवारी केवळ त्या नमुन्याचे वर्णन करते. ती कोणत्याही व्यक्ती, अधिकारी, कंत्राटदार वा संस्थेविरुद्धचा निष्कर्ष नाही आणि तशी कधीही वाचली जाऊ नये.',
  'Every record produced anywhere in the platform - every ward, department, intelligence item, decision case, evidence record and audit event - carries a':
    'मंचात कोठेही तयार होणाऱ्या प्रत्येक नोंदीस - प्रत्येक प्रभाग, विभाग, बुद्धिमत्ता बाब, निर्णय प्रकरण, पुरावा नोंद आणि लेखापरीक्षा घटना - असतो',
  'Every record the answer rests on. Select one to open its full provenance chain.':
    'उत्तर ज्या नोंदींवर आधारित आहे त्या प्रत्येक नोंदी. संपूर्ण उगमसाखळी उघडण्यासाठी एक निवडा.',
  'Every recorded AI incident and its lifecycle position.':
    'नोंदवलेली प्रत्येक कृत्रिम बुद्धिमत्ता घटना आणि तिचे जीवनचक्रातील स्थान.',
  'Every recorded security event within scope. Select a row to open the full record.':
    'व्याप्तीतील प्रत्येक नोंदवलेली सुरक्षा घटना. संपूर्ण नोंद उघडण्यासाठी ओळ निवडा.',
  'Every screen in this platform is built to these eleven principles without exception. They are not aspirational - they are enforced in code, not merely stated here, and the verification tab exercises the enforcement points behind seven of them.':
    'या मंचावरील प्रत्येक पडदा अपवादाशिवाय या अकरा तत्त्वांनुसार बांधलेला आहे. ही केवळ आकांक्षा नाहीत - ती येथे नुसती लिहिलेली नसून संकेतावलीत अंमलात आणलेली आहेत, आणि पडताळणी पट्टी त्यांपैकी सातांमागील अंमलबजावणी बिंदू प्रत्यक्ष तपासते.',
  'Every screen, figure and action is gated by the permission engine — enforced in the data layer, not by hiding links.':
    'प्रत्येक पडदा, आकडा आणि कृती परवानगी प्रणालीने नियंत्रित होते — दुवे लपवून नव्हे, तर माहिती स्तरावरच अंमलात आणून.',
  'Every source': 'प्रत्येक स्रोत',
  'Every such field is minimised, banded or dropped at the adapter before it enters the platform store — open a source and read its schema tab to see exactly which fields those are and what happens to each. In a production deployment each of these feeds additionally requires a completed privacy impact assessment and a signed data-sharing agreement before it may be provisioned; nothing here implies either exists.':
    'अशा प्रत्येक क्षेत्राचे मंचाच्या कोशात येण्यापूर्वी अडॅप्टरवरच किमानीकरण, पट्टीकरण किंवा वगळणी केली जाते — नेमकी कोणती क्षेत्रे आणि प्रत्येकाचे काय होते हे पाहण्यासाठी स्रोत उघडून त्याची संरचना पट्टी वाचा. उत्पादन तैनातीत यांपैकी प्रत्येक प्रवाहासाठी तो पुरवण्याआधी पूर्ण झालेले गोपनीयता परिणाम मूल्यांकन आणि स्वाक्षरीकृत माहिती-विनिमय करार आवश्यक असतो; यांपैकी काहीही अस्तित्वात असल्याचे येथे सूचित होत नाही.',
  'Every treatment facility and trunk-sewer reach ranked by utilisation. Nodes above the 100% reference line are running above design capacity.':
    'प्रत्येक प्रक्रिया सुविधा आणि मुख्य मलवाहिनी भाग वापरानुसार क्रमवार. 100% संदर्भ रेषेवरील नोड रचना क्षमतेपेक्षा अधिक चालत आहेत.',
  'Every ward · {0}': 'प्रत्येक प्रभाग · {0}',
  'Every ward × condition combination at or above a 50/100 modelled outbreak signal, ranked by strength. This is a modelled signal for prioritising field verification, not a confirmed outbreak declaration.':
    '50/100 किंवा त्याहून अधिक प्रतिरूपित उद्रेक संकेत असलेला प्रत्येक प्रभाग × स्थिती संयोग, तीव्रतेनुसार क्रमवार. क्षेत्रीय पडताळणीस प्राधान्य देण्यासाठीचा हा प्रतिरूपित संकेत आहे, उद्रेकाची निश्चित घोषणा नाही.',
  'Every ward carrying a review candidate, ranked by indicative annual value. Row click scopes the scorecard above.':
    'पुनरावलोकन प्रकरण असलेला प्रत्येक प्रभाग, निर्देशात्मक वार्षिक मूल्यानुसार क्रमवार. ओळीवर टिचकी मारल्यास वरील गुणपत्रिकेची व्याप्ती बदलते.',
  'Every ward ranked from lowest to highest desilting completion against the 100% pre-monsoon target.':
    '100% पावसाळापूर्व लक्ष्याच्या तुलनेत गाळ काढणीच्या पूर्ततेनुसार सर्वात कमीपासून सर्वाधिकपर्यंत क्रमवार प्रत्येक प्रभाग.',
  "Every zone's supply-demand balance and service quality. Click a zone row, or a ward on the map, to drill down to assets.":
    'प्रत्येक झोनचा पुरवठा-मागणी समतोल आणि सेवा गुणवत्ता. मालमत्तांपर्यंत तपशीलवेध घेण्यासाठी झोनच्या ओळीवर किंवा नकाशावरील प्रभागावर टिचकी मारा.',
  'Everything on this page is computed from records the corporation already holds - awarded value, released payment, recorded milestones, inspection observations and linked complaints. Time extensions and cost variations are granted through process and are frequently justified. An indicator means a figure warrants departmental attention and reconciliation; it does not mean a supplier has done anything wrong, and this screen cannot and does not make that determination.':
    'या पानावरील सर्व काही महानगरपालिकेकडे आधीच असलेल्या नोंदींवरून गणले जाते - कार्यादेश मूल्य, अदा केलेले देयक, नोंदवलेले टप्पे, तपासणी निरीक्षणे आणि जोडलेल्या तक्रारी. मुदतवाढी व खर्चातील फरक प्रक्रियेद्वारे मंजूर होतात आणि अनेकदा समर्थनीय असतात. निर्देशक म्हणजे एखादा आकडा विभागीय लक्ष व ताळमेळाची गरज दर्शवतो; त्याचा अर्थ पुरवठादाराने काही चूक केली असा नाही, आणि हा पडदा तसा निर्णय देऊ शकत नाही व देतही नाही.',
  'Evidence and lineage provenance chain': 'पुरावा व उगमसाखळी - उगम शृंखला',
  'Evidence before recommendation': 'शिफारशीपूर्वी पुरावा',
  'Evidence corpus': 'पुरावा संग्रह',
  'Evidence records reachable': 'उपलब्ध पुरावा नोंदी',
  'Evidence-backed': 'पुराव्यावर आधारित',
  'Evidence-backed share': 'पुराव्यावर आधारित वाटा',
  'Exceeding limits': 'मर्यादा ओलांडत आहेत',
  'Exceeds limit': 'मर्यादा ओलांडते',
  'Executive band': 'कार्यकारी पट्टा',
  'Executive brief': 'कार्यकारी टिपण',
  'Executive title': 'कार्यकारी पदनाम',
  'Exemption ground': 'सवलतीचा आधार',
  'exist in this platform&apos;s governance register that your current role and classification ceiling do not permit you to read. Consistent with least privilege, this page does not disclose which - a dataset you may not read is omitted entirely, not shown redacted. If you believe this is incorrect for your responsibilities, raise a scope review through Access Governance.':
    'या मंचाच्या कारभार नोंदवहीत अस्तित्वात आहेत, परंतु तुमची सध्याची भूमिका व वर्गीकरण मर्यादा तुम्हाला ती वाचण्याची परवानगी देत नाही. किमान अधिकाराच्या तत्त्वानुसार, ती कोणती हे हे पान उघड करत नाही - तुम्हाला वाचता येणार नाही असा माहितीसंच गाळून दाखवण्याऐवजी पूर्णपणे वगळला जातो. तुमच्या जबाबदाऱ्यांसाठी हे चुकीचे वाटत असल्यास, प्रवेश कारभारमार्फत व्याप्ती पुनरावलोकनाची मागणी करा.',
  'Expandable permission list': 'विस्तारता येणारी परवानगी यादी',
  'Expanded': 'विस्तारित',
  'Expectation: {0}': 'अपेक्षा: {0}',
  'Expenditure': 'खर्च',
  'Experience': 'अनुभव',
  'Experimental': 'प्रायोगिक',
  'Export audit trail': 'लेखापरीक्षा मागोवा निर्यात',
  'Export completed: {0} record(s) matching the current filters, {1}. The export itself has been written to the audit trail below.':
    'सध्याच्या गाळण्यांशी जुळणाऱ्या {0} नोंदींची निर्यात पूर्ण, {1}. ही निर्यात स्वतःच खालील लेखापरीक्षा मागोव्यात नोंदवली गेली आहे.',
  'Export the audit trail': 'लेखापरीक्षा मागोवा निर्यात करा',
  'Exposure requiring departmental attention - not findings.':
    'विभागीय लक्ष आवश्यक असलेली जोखीम - निष्कर्ष नाहीत.',
  'Exposures no single departmental view reveals': 'कोणत्याही एका विभागीय दृश्यातून न दिसणाऱ्या जोखमी',
  'Extrapolated annual value, full register': 'विस्तारित वार्षिक मूल्य, संपूर्ण नोंदवही',
  'Facilities above the surge threshold': 'वाढीव भार मर्यादेवरील सुविधा',
  'Facilities in flood-exposed wards': 'पूरप्रवण प्रभागांतील सुविधा',
  'Facilities in service': 'सेवेत असलेल्या सुविधा',
  'Facilities on the register': 'नोंदवहीतील सुविधा',
  'Facilities over capacity': 'क्षमतेपलीकडील सुविधा',
  'Facilities over capacity and compliance below the discharge norm are flagged directly.':
    'क्षमतेपलीकडे चालणाऱ्या सुविधा आणि विसर्ग प्रमाणाखालील अनुपालन थेट चिन्हांकित केले जाते.',
  'Facilities with the lowest current road accessibility index - the most exposed to approach disruption during flooding.':
    'सध्या सर्वात कमी रस्ता सुलभता निर्देशांक असलेल्या सुविधा - पूरकाळात पोहोचण्याच्या अडथळ्यास सर्वाधिक खुल्या.',
  'Facility map and ward coverage': 'सुविधा नकाशा व प्रभाग व्याप्ती',
  'Facility register': 'सुविधा नोंदवही',
  'Failing evaluation': 'मूल्यमापनात अनुत्तीर्ण',
  'Failing pipeline jobs': 'अपयशी प्रक्रियामार्ग कामे',
  'Failover posture': 'पर्यायी यंत्रणा स्थिती',
  'Fastest-falling ward': 'सर्वात वेगाने घसरणारा प्रभाग',
  'Faults in the feed itself. An ingestion fault is never recorded as a departmental failing.':
    'प्रवाहातच असलेले बिघाड. ग्रहणातील बिघाड कधीही विभागाचे अपयश म्हणून नोंदवला जात नाही.',
  'Federated institutional single sign-on replacing the demonstration profile switcher, so every principal is a real, individually accountable officer.':
    'प्रात्यक्षिक व्यक्तिरेखा बदलणाऱ्या सोयीऐवजी संस्थात्मक एकत्रित प्रवेश प्रणाली, जेणेकरून प्रत्येक वापरकर्ता खराखुरा, वैयक्तिकरीत्या जबाबदार अधिकारी असेल.',
  'Fee collection': 'शुल्क वसुली',
  'Feed': 'प्रवाह',
  'Field officer title': 'क्षेत्रीय अधिकारी पदनाम',
  'Field report': 'क्षेत्रीय अहवाल',
  'field set to': 'क्षेत्र यावर निश्चित',
  'Field updates': 'क्षेत्रीय अद्यतने',
  'Fill shows the worst locality composite in each ward. Illustrative spatial representation.':
    'रंगभरणी प्रत्येक प्रभागातील सर्वात वाईट वस्ती एकत्रित गुण दर्शवते. उदाहरणादाखल भौगोलिक मांडणी.',
  'Filter by approval status': 'मान्यता स्थितीनुसार गाळणी',
  'Filter by confidence': 'विश्वासार्हतेनुसार गाळणी',
  'Filter by currency': 'चलनानुसार गाळणी',
  'Filter by defect type': 'दोष प्रकारानुसार गाळणी',
  'Filter by department': 'विभागानुसार गाळणी',
  'Filter by evaluation status': 'मूल्यमापन स्थितीनुसार गाळणी',
  'Filter by facility type': 'सुविधा प्रकारानुसार गाळणी',
  'Filter by incident type': 'घटना प्रकारानुसार गाळणी',
  'Filter by maturity': 'परिपक्वतेनुसार गाळणी',
  'Filter by model': 'प्रारूपानुसार गाळणी',
  'Filter by origin': 'उगमानुसार गाळणी',
  'Filter by owner department': 'जबाबदार विभागानुसार गाळणी',
  'Filter by policy status': 'धोरण स्थितीनुसार गाळणी',
  'Filter by protection status': 'संरक्षण स्थितीनुसार गाळणी',
  'Filter by record kind': 'नोंद प्रकारानुसार गाळणी',
  'Filter by register': 'नोंदवहीनुसार गाळणी',
  'Filter by review status': 'पुनरावलोकन स्थितीनुसार गाळणी',
  'Filter by risk indicators': 'जोखीम निर्देशकांनुसार गाळणी',
  'Filter by segment type': 'विभाग प्रकारानुसार गाळणी',
  'Filter by service category': 'सेवा श्रेणीनुसार गाळणी',
  'Filter by signal stacking': 'संकेत साचण्यानुसार गाळणी',
  'Filter by standing': 'सद्यस्थितीनुसार गाळणी',
  'Filter by station type': 'केंद्र प्रकारानुसार गाळणी',
  'Filter by use case': 'वापर प्रकरणानुसार गाळणी',
  'Filter by who holds the work': 'काम कोणाकडे आहे त्यानुसार गाळणी',
  'Filter by zone type': 'झोन प्रकारानुसार गाळणी',
  'Filtered result': 'गाळलेला निष्कर्ष',
  'Filtered to {0}': '{0} पुरते गाळले',
  'Financial Health Index': 'वित्तीय स्थिती निर्देशांक',
  'Financial impact under decision': 'निर्णयाधीन आर्थिक परिणाम',
  'Financial impact under decision:': 'निर्णयाधीन आर्थिक परिणाम:',
  'Financial position progression': 'वित्तीय स्थितीची वाटचाल',
  'Financial record': 'वित्तीय नोंद',
  'Fire and building-collapse incidents, response teams and station readiness.':
    'आग व इमारत कोसळण्याच्या घटना, प्रतिसाद पथके आणि केंद्र सज्जता.',
  'Fire Station': 'अग्निशमन केंद्र',
  'Flag a statistical departure from cohort comparables for human reconciliation.':
    'समगटातील तुलनात्मक नोंदींपासूनचे सांख्यिकीय विचलन मानवी ताळमेळासाठी चिन्हांकित करणे.',
  'Flagged and blocked requests': 'चिन्हांकित व अडवलेल्या विनंत्या',
  'Flagged at {0}% bed occupancy or an emergency load index of {1} or higher.':
    '{0}% खाट भोगवटा किंवा {1} किंवा त्याहून अधिक आपत्कालीन भार निर्देशांकावर चिन्हांकित.',
  'Flagged rows meet both a vacancy threshold of':
    'चिन्हांकित ओळी दोन्ही अटी पूर्ण करतात - रिक्त पदांची मर्यादा',
  'Flags enabled': 'कार्यान्वित ध्वज',
  'Flat': 'सपाट',
  'Flood and drainage exposure': 'पूर व जलनिस्सारण जोखीम',
  'Flood and extreme-weather incidents, drainage readiness and pumping capacity.':
    'पूर व अतिटोकाच्या हवामानाच्या घटना, जलनिस्सारण सज्जता आणि उपसा क्षमता.',
  'Flood incidents currently detected, validated or active - including any raised from the scenario tool above.':
    'सध्या शोधलेल्या, पडताळलेल्या किंवा सुरू असलेल्या पूर घटना - वरील परिस्थिती साधनातून उपस्थित केलेल्या घटनांसह.',
  'Flood risk, ward readiness and compound-event scenarios, including the river and drain behaviour that governs inundation here.':
    'पूर जोखीम, प्रभाग सज्जता आणि संयुक्त-घटना परिस्थिती, येथील जलमय होण्यावर परिणाम करणाऱ्या नदी व गटार वर्तनासह.',
  'Flood-prone settlements': 'पूरप्रवण वसाहती',
  'Flood-prone wards, elevated signal': 'पूरप्रवण प्रभाग, वाढीव संकेत',
  'Focus node centred, first-degree neighbours on the inner ring, second-degree on the outer ring. Node size reflects institutional weight; colour reflects entity kind; a red ring marks a recorded severity.':
    'केंद्रस्थ नोड मध्यभागी, पहिल्या पातळीचे शेजारी आतल्या वर्तुळावर, दुसऱ्या पातळीचे बाहेरच्या वर्तुळावर. नोडचा आकार संस्थात्मक महत्त्व दर्शवतो; रंग घटक प्रकार दर्शवतो; लाल कडे नोंदवलेली तीव्रता दर्शवते.',
  'Focused indicator': 'केंद्रस्थ निर्देशक',
  'for a new line': 'नव्या ओळीसाठी',
  'for this deployment. Every service method in the data-access layer accepts the acting principal first and filters its source collection to that principal&apos;s own tenant before any further permission or scope check is applied. In this single-tenant demonstration build the filter is a deliberate no-op - there is only one tenant to filter to - but the enforcement point exists exactly where it would sit in a genuine multi-tenant deployment, so a second municipal body&apos;s data would be excluded at the same choke point, not left to individual screens to remember.':
    'या तैनातीसाठी. माहिती-प्रवेश स्तरातील प्रत्येक सेवा पद्धत प्रथम कार्यरत वापरकर्ता स्वीकारते आणि पुढील कोणतीही परवानगी वा व्याप्ती तपासणी लागू होण्यापूर्वी आपला स्रोत संच त्या वापरकर्त्याच्या स्वतःच्या आस्थापनेपुरता गाळते. या एक-आस्थापना प्रात्यक्षिक आवृत्तीत ही गाळणी जाणीवपूर्वक निष्क्रिय आहे - गाळण्यासाठी एकच आस्थापना आहे - परंतु अंमलबजावणी बिंदू नेमका तेथेच आहे जेथे तो खऱ्या बहु-आस्थापना तैनातीत असेल, म्हणजे दुसऱ्या महानगरपालिकेची माहिती याच एकाच बिंदूवर वगळली जाईल, ती लक्षात ठेवण्याचे काम स्वतंत्र पडद्यांवर सोडले जाणार नाही.',
  'Forecast (Year-End)': 'अंदाज (वर्षअखेर)',
  'Forecast variance measures how far departmental year-end forecasts sit from the approved position. It is a measure of how well the corporation forecasts itself - a governance signal. It is not a prediction of the year-end outturn and must not be read as one.':
    'अंदाज फरक हा विभागीय वर्षअखेर अंदाज मंजूर स्थितीपासून किती दूर आहेत हे मोजतो. महानगरपालिका स्वतःचा अंदाज किती चांगला बांधते याचे हे मोजमाप आहे - एक कारभारविषयक संकेत. हा वर्षअखेर प्रत्यक्ष निष्पत्तीचा अंदाज नाही आणि तसा वाचला जाऊ नये.',
  'Forecast vs annual target - by stream': 'अंदाज विरुद्ध वार्षिक लक्ष्य - प्रवाहनिहाय',
  'Formal sign-off from an AI governance authority for each approved use case, prompt template and risk disposition.':
    'प्रत्येक मंजूर वापर प्रकरण, सूचना नमुना आणि जोखीम निर्णयासाठी कृत्रिम बुद्धिमत्ता कारभार प्राधिकाऱ्याची औपचारिक मान्यता.',
  'Formatting is presentation, never derivation. Changing the numbering convention re-renders a figure in a different dialect; it does not recompute it, round it differently or alter what any service returned. Exports taken after a change carry the same values in the same convention you are reading on screen, so a file and the screen it came from can always be reconciled.':
    'स्वरूप हे केवळ सादरीकरण आहे, व्युत्पत्ती कधीही नाही. अंकपद्धतीची संकेतपद्धत बदलल्यास आकडा वेगळ्या बोलीत पुन्हा दाखवला जातो; त्यामुळे त्याची फेरगणना होत नाही, तो वेगळ्या पद्धतीने पूर्णांकित होत नाही, किंवा कोणत्याही सेवेने परत केलेले मूल्य बदलत नाही. बदलानंतर घेतलेल्या निर्यातींत तीच मूल्ये तुम्ही पडद्यावर वाचत असलेल्या त्याच संकेतपद्धतीत असतात, त्यामुळे फाइल आणि ती ज्या पडद्यावरून आली त्याचा ताळमेळ नेहमीच घालता येतो.',
  'Forward-looking: the modelled year-end forecast against the full annual target for each stream.':
    'भविष्यवेधी: प्रत्येक प्रवाहासाठी संपूर्ण वार्षिक लक्ष्याच्या तुलनेत प्रतिरूपित वर्षअखेर अंदाज.',
  'Four gates: integration design review · departmental data-sharing agreement · adapter built and tested · endpoint provisioned. A connector in simulation has cleared three; the fourth is precisely what this environment does not have, which is why nothing here is described as live.':
    'चार टप्पे: एकात्मीकरण रचना पुनरावलोकन · विभागीय माहिती-विनिमय करार · अडॅप्टर तयार व चाचणी · अंतिम बिंदू उपलब्ध. नक्कल स्वरूपातील जोडणीने तीन टप्पे पार केले आहेत; चौथा टप्पा नेमका या वातावरणात नाही, म्हणूनच येथे कशाचेही वर्णन प्रत्यक्ष म्हणून केलेले नाही.',
  'Four structural conditions, weighted to one hundred. None of them moves because a ward office works well or badly.':
    'चार संरचनात्मक स्थिती, शंभर गुणांत भारित. प्रभाग कार्यालय चांगले किंवा वाईट काम करते म्हणून यांपैकी काहीही बदलत नाही.',
  'Fourteen illustrative principals spanning executive, senior, operational and oversight bands, each with a distinct scope.':
    'कार्यकारी, वरिष्ठ, कामकाज आणि देखरेख पट्ट्यांतील चौदा उदाहरणादाखल वापरकर्ते, प्रत्येकाची व्याप्ती वेगळी.',
  'Free-flow speed': 'मुक्त वेग',
  'Freshness expectation': 'ताजेपणाची अपेक्षा',
  'Freshness expectation is {0}': 'ताजेपणाची अपेक्षा {0} आहे',
  'Freshness reference: generated {0}.': 'ताजेपणा संदर्भ: {0} रोजी तयार.',
  'From date': 'पासूनचा दिनांक',
  'Full': 'पूर्ण',
  'Full audit register': 'संपूर्ण लेखापरीक्षा नोंदवही',
  'Full permission list': 'संपूर्ण परवानगी यादी',
  'Fully reviewed': 'पूर्ण पुनरावलोकन झाले',
  'Functional hospital beds per 10,000 ward residents, scaled 0–100 for map shading. Higher is better coverage.':
    'दर 10,000 प्रभाग रहिवाशांमागे कार्यरत रुग्णालय खाटा, नकाशा रंगछटेसाठी 0–100 प्रमाणात. अधिक म्हणजे अधिक चांगली व्याप्ती.',
  'Furthest above its line': 'आपल्या रेषेच्या सर्वाधिक वर',
  'Furthest below its line': 'आपल्या रेषेच्या सर्वाधिक खाली',
  'Generated {0}': '{0} रोजी तयार',
  'Generated {0} · Model {1} · For {2}': '{0} रोजी तयार · प्रारूप {1} · {2} साठी',
  'Generated at': 'तयार झाल्याची वेळ',
  'Generating executive brief': 'कार्यकारी टिपण तयार होत आहे',
  'Generation': 'निर्मिती',
  'Give the source a name of at least 3 characters.': 'स्रोतास किमान 3 अक्षरांचे नाव द्या.',
  'Go to Executive Overview': 'कार्यकारी आढाव्याकडे जा',
  'Good': 'चांगले',
  'Governed by role': 'भूमिकेनुसार नियंत्रित',
  'Government acts this agent is categorically barred from performing, regardless of confidence.':
    'विश्वासार्हता कितीही असली तरी हा प्रतिनिधी ज्या शासकीय कृत्यांपासून पूर्णपणे प्रतिबंधित आहे ती.',
  'Grouped by locality and service category - the unit a department can act on.':
    'वस्ती व सेवा श्रेणीनुसार गटबद्ध - विभाग ज्या घटकावर कृती करू शकतो तो.',
  'Grouped comparison': 'गटबद्ध तुलना',
  'Growth &amp; space pressure': 'वाढ &amp; जागेवरील ताण',
  'Guardrails': 'संरक्षक मर्यादा',
    'Hazard preparedness detail': 'धोका सज्जता तपशील',
  'Head': 'प्रमुख',
  'Headroom': 'शिल्लक वाव',
  'Health & Environment': 'आरोग्य व पर्यावरण',
  "Health score by month over the last {0} months, against the {1}-point intervention threshold. The rightmost month is each ward's live figure, unchanged from Ward Intelligence.":
    'गेल्या {0} महिन्यांतील महिनानिहाय आरोग्य गुण, {1}-गुणांच्या हस्तक्षेप मर्यादेच्या तुलनेत. सर्वात उजवीकडचा महिना हा प्रत्येक प्रभागाचा प्रत्यक्ष आकडा असून तो प्रभाग बुद्धिमत्तेवरील आकड्याइतकाच आहे.',
  'Hectares of maintained open space per thousand residents - the figure a development plan is judged against.':
    'दर हजार रहिवाशांमागे देखभाल केलेल्या मोकळ्या जागेचे हेक्टर - विकास आराखडा ज्या आकड्यावर तपासला जातो तो.',
  'Held by': 'यांच्याकडे',
  'Held by {0}': '{0} यांच्याकडे',
  'Held by a department or a review body — not by this platform.':
    'विभाग किंवा पुनरावलोकन मंडळाकडे — या मंचाकडे नाही.',
  'Held by anyone': 'कोणाकडेही',
  'Held by nobody': 'कोणाकडेही नाही',
  'Held in this session only, across all three engines.': 'तिन्ही प्रणालींमध्ये केवळ या सत्रापुरते ठेवलेले.',
  'Held under the Street Vendors Act, 2014. {0} zones await the statutory survey and {1} have no Town Vending Committee constituted - both are preconditions the corporation has to meet before a certificate can lawfully issue.':
    'पथविक्रेता अधिनियम, 2014 अन्वये ठेवलेले. {0} क्षेत्रे वैधानिक सर्वेक्षणाच्या प्रतीक्षेत आहेत आणि {1} क्षेत्रांत नगर विक्री समिती गठित झालेली नाही - प्रमाणपत्र कायदेशीररीत्या देण्यापूर्वी महानगरपालिकेने पूर्ण करावयाच्या या दोन्ही पूर्वअटी आहेत.',
  'Held-out cases': 'राखून ठेवलेली प्रकरणे',
  'Held, but not cleanly': 'टिकले, पण निर्दोषपणे नाही',
  'High or critical': 'उच्च किंवा अतितीव्र',
  'High risk class': 'उच्च जोखीम वर्ग',
  'High risk-class models': 'उच्च जोखीम वर्गातील प्रारूपे',
  'High Tide Intelligence': 'मोठी भरती बुद्धिमत्ता',
  'High tide windows blocking discharge': 'विसर्ग अडवणाऱ्या मोठ्या भरतीच्या वेळा',
  'high-priority defects': 'उच्च प्राधान्य दोष',
  'High-priority issues': 'उच्च प्राधान्य बाबी',
  'High-risk wards': 'उच्च जोखमीचे प्रभाग',
  'Highest current outbreak signal': 'सध्याचा सर्वाधिक उद्रेक संकेत',
  'Highest operational risks': 'सर्वाधिक कामकाज जोखमी',
  'Highest outbreak signal {0}/100 across {1} ward(s)': '{1} प्रभागांमधील सर्वाधिक उद्रेक संकेत {0}/100',
  'Highest-priority open defects by published score, {0}. Excludes repaired and verified-closed defects.':
    'प्रकाशित गुणांनुसार सर्वोच्च प्राधान्याचे प्रलंबित दोष, {0}. दुरुस्त व पडताळून बंद केलेले दोष वगळले आहेत.',
  'Highest-risk works': 'सर्वाधिक जोखमीची कामे',
  'Highest-severity open intelligence, city-wide.': 'सर्वाधिक तीव्रतेची प्रलंबित बुद्धिमत्ता, शहरव्यापी.',
  'highlighted · congestion': 'ठळक केलेले · वाहतूक कोंडी',
  'highlighted on the map · vehicle': 'नकाशावर ठळक केलेले · वाहन',
  'Holds {0} permission(s) across {1} of {2} resources and {3} of {4} action types.':
    '{2} पैकी {1} साधनांवर आणि {4} पैकी {3} कृती प्रकारांवर {0} परवानग्या आहेत.',
  'Hospital · {0} · occupancy {1}%': 'रुग्णालय · {0} · भोगवटा {1}%',
  'Hospital · accessibility {0}/100': 'रुग्णालय · सुलभता {0}/100',
  'Hospital accessibility': 'रुग्णालय सुलभता',
  'Hospital Accessibility Risk': 'रुग्णालय सुलभता जोखीम',
  'Hospital registration units and ward offices within your authorised ward scope.':
    'तुमच्या प्राधिकृत प्रभाग व्याप्तीतील रुग्णालय नोंदणी कक्ष व प्रभाग कार्यालये.',
  'Hospital utilisation summary': 'रुग्णालय वापर सारांश',
  'Hospitals and fire / disaster / ambulance emergency stations.':
    'रुग्णालये आणि अग्निशमन / आपत्ती / रुग्णवाहिका आपत्कालीन केंद्रे.',
  'Hospitals:': 'रुग्णालये:',
  'Hotspots': 'समस्याक्षेत्रे',
  'Hours a circuit was actually lit against the hours it should have been. A circuit dark at 21:00 is a safety matter, not a billing one.':
    'मार्गिका जितके तास प्रज्वलित असायला हवी होती त्या तुलनेत ती प्रत्यक्षात जितके तास प्रज्वलित होती ते. 21:00 वाजता अंधारात असलेली मार्गिका ही सुरक्षेची बाब आहे, देयकाची नाही.',
  'How a decision case moves': 'निर्णय प्रकरण कसे पुढे सरकते',
  'How difficulty is scored': 'अडचणीचे गुणांकन कसे होते',
  'How each tier is designed to survive the loss of a zone or component.':
    'झोन किंवा घटक निकामी झाल्यास प्रत्येक स्तर तो कसा सहन करेल याची रचना.',
  'How every figure in the platform is spoken. These change presentation only — no underlying value, derivation or seed moves.':
    'मंचावरील प्रत्येक आकडा कसा मांडला जातो. यामुळे केवळ सादरीकरण बदलते — मूळ मूल्य, व्युत्पत्ती किंवा बीज यांत काहीही बदल होत नाही.',
  'How expectation is set': 'अपेक्षा कशी ठरवली जाते',
  "How one municipal body's data is kept apart from every other, and which bodies this same build can be deployed against.":
    'एका महानगरपालिकेची माहिती इतर सर्वांपासून वेगळी कशी ठेवली जाते, आणि हीच आवृत्ती कोणत्या संस्थांवर तैनात करता येते.',
  'How the index is composed': 'निर्देशांक कसा तयार होतो',
  'How the need score was formed': 'गरज गुण कसा तयार झाला',
  "How this deployment keeps one municipal body's data separate from every other.":
    'ही तैनाती एका महानगरपालिकेची माहिती इतर सर्वांपासून वेगळी कशी ठेवते.',
  'How this index is computed': 'हा निर्देशांक कसा गणला जातो',
  'How this platform looks and behaves for you. Held in this browser, applied the moment they are set.':
    'हा मंच तुमच्यासाठी कसा दिसतो व वागतो. या ब्राउझरमध्ये ठेवलेले, निश्चित करताच लागू होणारे.',
  'How this question was read': 'हा प्रश्न कसा वाचला गेला',
  'Human approval rate': 'मानवी मान्यता दर',
  'Human approval rate over the last 30 days:': 'गेल्या 30 दिवसांतील मानवी मान्यता दर:',
  'Human authority before AI authority': 'कृत्रिम बुद्धिमत्तेच्या अधिकारापूर्वी मानवी अधिकार',
  'Human checkpoint': 'मानवी तपासणी बिंदू',
  'Human Decision': 'मानवी निर्णय',
  'Human oversight': 'मानवी देखरेख',
  'Human oversight of AI recommendations': 'कृत्रिम बुद्धिमत्ता शिफारशींवरील मानवी देखरेख',
  'Human oversight register': 'मानवी देखरेख नोंदवही',
  'Human Review': 'मानवी पुनरावलोकन',
  'Human-in-the-loop enforcement points': 'मानवी सहभाग अनिवार्य असलेले अंमलबजावणी बिंदू',
  'ICU beds': 'अतिदक्षता खाटा',
  'Identity & access': 'ओळख व प्रवेश',
  'Identity and branding configuration for this deployment.': 'या तैनातीसाठी ओळख व बोधचिन्ह मांडणी.',
  'If this stage stops': 'हा टप्पा थांबल्यास',
  'If your responsibilities require access to a module that does not appear here, raise a scope amendment through Access Governance rather than navigating to it directly.':
    'तुमच्या जबाबदाऱ्यांसाठी येथे न दिसणाऱ्या विभागाचा प्रवेश आवश्यक असल्यास, थेट तेथे जाण्याऐवजी प्रवेश कारभारमार्फत व्याप्ती दुरुस्तीची मागणी करा.',
  'Illustrative spatial position within the city; shading shows composite risk across all wards. Click another ward to change context.':
    'शहरातील उदाहरणादाखल भौगोलिक स्थान; रंगछटा सर्व प्रभागांतील एकत्रित जोखीम दर्शवते. संदर्भ बदलण्यासाठी दुसऱ्या प्रभागावर टिचकी मारा.',
  'Illustrative ward map shaded by average asset condition index for the current scope.':
    'सध्याच्या व्याप्तीसाठी सरासरी मालमत्ता स्थिती निर्देशांकानुसार रंगछटा दिलेला उदाहरणादाखल प्रभाग नकाशा.',
  'Illustrative ward map shaded by collection efficiency for the segment scope selected above. Click a ward to focus the register above.':
    'वर निवडलेल्या विभाग व्याप्तीसाठी वसुली कार्यक्षमतेनुसार रंगछटा दिलेला उदाहरणादाखल प्रभाग नकाशा. वरील नोंदवही केंद्रित करण्यासाठी प्रभागावर टिचकी मारा.',
  'Impact assessment, not a hypothetical.': 'परिणाम मूल्यांकन, काल्पनिक मांडणी नाही.',
  'Impact: {0}': 'परिणाम: {0}',
  'Implemented against outstanding, by category. Select a bar to filter both lists.':
    'श्रेणीनुसार, प्रलंबितांच्या तुलनेत अंमलात आणलेले. दोन्ही याद्या गाळण्यासाठी पट्टी निवडा.',
  'Implemented in demonstration environment': 'प्रात्यक्षिक वातावरणात अंमलात',
  'Implemented in this demonstration': 'या प्रात्यक्षिकात अंमलात',
  'In progress': 'सुरू आहे',
  'In Repair': 'दुरुस्तीत',
  'in that quartile, not the administration of it. A band marked critical is the hardest ground in the corporation to run, which is a statement about the ward and never about the people running it.':
    'त्या चतुर्थकातील, तिच्या प्रशासनाचे नव्हे. अतितीव्र म्हणून चिन्हांकित पट्टा म्हणजे महानगरपालिकेतील चालवण्यास सर्वात कठीण भूभाग, जे त्या प्रभागाबद्दलचे विधान आहे, तो चालवणाऱ्या माणसांबद्दल कधीही नाही.',
  'In transit': 'संक्रमणात',
  'In work after three months': 'तीन महिन्यांनंतर कामावर',
  'In work after training': 'प्रशिक्षणानंतर कामावर',
  'Incident · {0} · {1}': 'घटना · {0} · {1}',
  'Incident lifecycle': 'घटना जीवनचक्र',
  'Incident map': 'घटना नकाशा',
  'Incident title': 'घटना शीर्षक',
  'incident(s) in 30 days ·': '30 दिवसांतील घटना ·',
  'Incidents': 'घटना',
  'Incidents in scope': 'व्याप्तीतील घटना',
  'Incidents of type Fire, or owned by the {0}, currently in the unified incident register.':
    'एकत्रित घटना नोंदवहीत सध्या असलेल्या आग प्रकारच्या, किंवा {0} यांच्याकडे असलेल्या घटना.',
  'Incidents recorded against this ward not yet resolved or reviewed.':
    'या प्रभागाविरुद्ध नोंदवलेल्या, अद्याप निराकरण किंवा पुनरावलोकन न झालेल्या घटना.',
  'Independent security assessment': 'स्वतंत्र सुरक्षा मूल्यांकन',
  'Independent toggles - combine any number of entity-class layers on the map at once.':
    'स्वतंत्र कळा - नकाशावर एकाच वेळी कितीही घटक-वर्ग स्तर एकत्र करा.',
  'Index {0}–{1}': 'निर्देशांक {0}–{1}',
  'Index methodology': 'निर्देशांक कार्यपद्धती',
  'Indicative annual value is a modelled estimate used to prioritise the queue. It is not an amount owed by anybody. Only the revised and collected figures represent demand actually raised by a named officer through the statutory assessment process.':
    'निर्देशात्मक वार्षिक मूल्य हा रांगेस प्राधान्य देण्यासाठी वापरलेला प्रतिरूपित अंदाज आहे. ती कोणाकडून येणे असलेली रक्कम नाही. केवळ सुधारित व वसूल आकडेच नामनिर्देशित अधिकाऱ्याने वैधानिक आकारणी प्रक्रियेतून प्रत्यक्ष उभी केलेली मागणी दर्शवतात.',
  'Indicative net position': 'निर्देशात्मक निव्वळ स्थिती',
  'Indicative saving from completing conversion: ₹{0} Cr a year':
    'रूपांतर पूर्ण केल्यास निर्देशात्मक बचत: वर्षाला ₹{0} कोटी',
  'Indicative value': 'निर्देशात्मक मूल्य',
  'Indicative value by rule tier': 'नियम स्तरानुसार निर्देशात्मक मूल्य',
  "Indicative value per sampled parcel, applied to the parcel count on the corporation's full assessment register. It assumes the sampled defect rate holds across the register, which a ward-scoped pilot is the correct way to test.":
    'नमुना म्हणून घेतलेल्या प्रत्येक भूखंडामागील निर्देशात्मक मूल्य, महानगरपालिकेच्या संपूर्ण आकारणी नोंदवहीतील भूखंड संख्येवर लागू केलेले. नमुन्यातील दोष दर संपूर्ण नोंदवहीत तसाच राहील असे ते गृहीत धरते, आणि ते तपासण्याचा योग्य मार्ग म्हणजे प्रभागापुरता प्रायोगिक प्रकल्प.',
  'Indicators': 'निर्देशक',
  'indicators (': 'निर्देशक (',
  'indicators are generated for this demonstration, because no comparable state-wide operational return exists in the public domain. Every metric carries its basis, and the two are never combined into a single composite score - a ranking that mixed them would look authoritative and mean nothing.':
    'निर्देशक या प्रात्यक्षिकासाठी तयार केलेले आहेत, कारण सार्वजनिक क्षेत्रात तुलना करण्याजोगे राज्यव्यापी कामकाज विवरण उपलब्ध नाही. प्रत्येक मापदंड आपला आधार नमूद करतो, आणि दोन्ही कधीही एकाच एकत्रित गुणांत मिसळले जात नाहीत - ते मिसळणारी क्रमवारी अधिकृत भासेल पण तिचा काहीही अर्थ राहणार नाही.',
  'Infrastructure Adequacy': 'पायाभूत सुविधा पर्याप्तता',
  'Infrastructure anchors': 'पायाभूत सुविधा आधारबिंदू',
  'Infrastructure and monsoon': 'पायाभूत सुविधा व पावसाळा',
  'Infrastructure asset · {0} · condition {1}/100': 'पायाभूत मालमत्ता · {0} · स्थिती {1}/100',
  'Infrastructure condition': 'पायाभूत सुविधा स्थिती',
  'Infrastructure failures, utility incidents and road disruption.':
    'पायाभूत सुविधांतील बिघाड, सुविधा घटना आणि रस्ते वाहतुकीतील अडथळा.',
  'Ingestion incidents': 'ग्रहण घटना',
  'Ingestion register': 'ग्रहण नोंदवही',
  'INR crore, indicative': 'रुपये कोटी, निर्देशात्मक',
  'Inspection': 'तपासणी',
  'Inspections': 'तपासण्या',
  'Institutional accent': 'संस्थात्मक रंगछटा',
  'Institutional audit trail': 'संस्थात्मक लेखापरीक्षा मागोवा',
  'Institutional explanation of the components currently exceeding their attention threshold.':
    'सध्या आपली लक्ष-मर्यादा ओलांडणाऱ्या घटकांचे संस्थात्मक स्पष्टीकरण.',
  'Integrations': 'एकात्मीकरणे',
  'Intelligence to accountable outcome': 'बुद्धिमत्तेपासून जबाबदार निष्पत्तीपर्यंत',
  'Intelligence, alert, incident and decision lifecycles progress only through declared transitions, several requiring a recorded reason.':
    'बुद्धिमत्ता, इशारा, घटना आणि निर्णय जीवनचक्रे केवळ घोषित संक्रमणांतूनच पुढे सरकतात, त्यांपैकी अनेकांसाठी नोंदवलेले कारण आवश्यक असते.',
    'Interface preferences': 'आंतरपृष्ठ पसंती',
  'Internal only': 'केवळ अंतर्गत',
  'Interruptions / complaints (30d)': 'खंड / तक्रारी (30 दि)',
  'Inverse of monsoon readiness score.': 'पावसाळी सज्जता गुणाच्या व्यस्त प्रमाणात.',
  'is held for: &quot;': 'यासाठी ठेवलेले आहे: &quot;',
  'is running': 'चालू आहे',
  'Isolated disruption': 'तुरळक अडथळा',
  'Issued': 'जारी',
  'Junction & closure impact': 'चौक व बंद रस्त्यांचा परिणाम',
    'km²': 'चौ. किमी',
  'Land composition': 'जमिनीची रचना',
  'Land for the dead is finite and cannot be replaced':
    'मृतांसाठीची जमीन मर्यादित आहे आणि तिची जागा दुसरी घेऊ शकत नाही',
  'Landfill': 'भरावभूमी',
  'Landfilled': 'भरावभूमीत टाकलेला',
  'Lands on': 'प्रवेशानंतरचे पान',
  "Lapsed licences as a share of the ward's whole register. The revenue this represents is already assessed - it is uncollected, not unassessed.":
    'प्रभागाच्या संपूर्ण नोंदवहीतील व्यपगत परवान्यांचा वाटा. यातून दिसणाऱ्या महसुलाची आकारणी आधीच झालेली आहे - तो अवसूल आहे, अनाकारित नाही.',
  'Last 30 days, modelled': 'गेले 30 दिवस, प्रतिरूपित',
  'Last assessed': 'शेवटची आकारणी झाली',
  'Last assessment': 'शेवटची आकारणी',
  'Last evaluated {0}': 'शेवटचे मूल्यमापन {0}',
  'Last incident': 'शेवटची घटना',
  'Last maintained {0}': 'शेवटची देखभाल {0}',
  'Last refreshed': 'शेवटचे नूतनीकरण',
  'Last reviewed': 'शेवटचे पुनरावलोकन',
  'Last run': 'शेवटची फेरी',
  'Last sign-in': 'शेवटचा प्रवेश',
  'Last sync': 'शेवटचे समक्रमण',
  'Latency': 'विलंब',
  'Latency distribution': 'विलंब वितरण',
  'Lawful reasons this candidate may require no action at all':
    'या प्रकरणी कोणतीही कारवाई आवश्यक नसण्याची कायदेशीर कारणे',
  'Lawful reasons this rule fires where nothing is wrong':
    'काहीही चुकीचे नसतानाही हा नियम लागू होण्याची कायदेशीर कारणे',
  'Layer between flood risk, ward readiness, drain risk and pump readiness. Markers show chronic waterlogging locations, pumping stations and hospitals. Click a ward or marker to filter the panels below.':
    'पूर जोखीम, प्रभाग सज्जता, गटार जोखीम आणि उपसा सज्जता यांचे स्तर एकावर एक ठेवा. खुणा नेहमी पाणी साचणारी ठिकाणे, उपसा केंद्रे आणि रुग्णालये दर्शवतात. खालील पटले गाळण्यासाठी प्रभागावर किंवा खुणेवर टिचकी मारा.',
  'Layer control': 'स्तर नियंत्रण',
  'Leaders · {0}': 'आघाडीवर · {0}',
  'Leakage indicators': 'गळती निर्देशक',
  'Least privilege': 'किमान अधिकार',
  'Least-served settlements': 'सर्वात कमी सेवा मिळणाऱ्या वसाहती',
  'Length by protection status': 'संरक्षण स्थितीनुसार लांबी',
  'Lesson carried forward': 'पुढे नेलेला धडा',
  'Lessons learned': 'शिकलेले धडे',
  'Level is not the same as direction': 'पातळी आणि दिशा एक नव्हे',
  'Licence register by ward and category': 'प्रभाग व श्रेणीनुसार परवाना नोंदवही',
  'Licences current': 'चालू परवाने',
  'Licences issued': 'जारी केलेले परवाने',
  'Life-safety exposure - {0} structure{1}': 'जीवसुरक्षा जोखीम - {0} बांधकाम{1}',
  'Lifecycle exposure - {0} asset{1}': 'जीवनचक्र जोखीम - {0} मालमत्ता{1}',
  'Likelihood / impact matrix': 'शक्यता / परिणाम कोष्टक',
  'Likelihood: {0}': 'शक्यता: {0}',
  'Lineage': 'उगमसाखळी',
  'Lineage catalogue': 'उगमसाखळी सूची',
  'Lineage graphs published': 'प्रकाशित उगमसाखळी आलेख',
  'Linked complaints': 'जोडलेल्या तक्रारी',
  'Linked projects ({0})': 'जोडलेले प्रकल्प ({0})',
  'Live permission engine tester': 'प्रत्यक्ष परवानगी प्रणाली चाचणी',
  'Live sample': 'प्रत्यक्ष नमुना',
  'Livelihoods estate': 'उपजीविका संकुल',
}
