/** Marathi catalogue, part 39. Keyed by the exact English source.
 * "For context" real-data footnotes across city/governance pages, plus AIEvaluationPage and CockpitBriefing. */
export const MR_PART_39: Record<string, string> = {
  'Evaluated once, applies to every tenant': 'एकदा मूल्यमापित, प्रत्येक टेनंटला लागू',
  "These runs score the model and prompt template themselves against the platform's AI gateway - they hold no corporation-specific data and are not scoped to a tenant. A model that passes here is approved for every corporation the reusable engine serves, not for Brihanmumbai alone; a corporation onboarded after this evaluation inherits the same verdict without a re-run.":
    'हे मूल्यमापन धावा मंचाच्या AI गेटवेविरुद्ध स्वतः मॉडेल आणि प्रॉम्प्ट टेम्प्लेटचे गुणांकन करतात - त्यांच्याकडे कोणतीही महानगरपालिका-विशिष्ट माहिती नसते आणि ते कोणत्याही टेनंटपुरते मर्यादित नसतात. येथे उत्तीर्ण होणारे मॉडेल पुनर्वापरयोग्य इंजिन सेवा देत असलेल्या प्रत्येक महानगरपालिकेसाठी मंजूर आहे, केवळ बृहन्मुंबईसाठी नव्हे; या मूल्यमापनानंतर सामील होणारी महानगरपालिका पुनर्चाचणीशिवाय तोच निष्कर्ष स्वीकारते.',
  "For context: a Praja Foundation RTI-based report (May 2024) counted {0} public toilet blocks across Mumbai's 24 wards - one seat per 752 males and one per 1,820 females; 69% of community blocks lack water, 60% lack electricity.":
    'संदर्भासाठी: प्रजा फाउंडेशनच्या माहिती अधिकार-आधारित अहवालानुसार (मे २०२४) मुंबईच्या २४ प्रभागांत {0} सार्वजनिक शौचालय गट मोजले गेले - दर ७५२ पुरुषांमागे एक आसन आणि दर १,८२० स्त्रियांमागे एक; ६९% सामुदायिक गटांत पाणी नाही, ६०% मध्ये वीज नाही.',
  'For context: BMC runs just {0} ABC centres against an estimated 90,000+ stray dogs, per BMC officials (Nov 2025). 4,03,374 dogs have been sterilised 1994-Dec 2023, with a 45,000/year target and ₹23 crore allocated for the current drive.':
    'संदर्भासाठी: BMC अधिकाऱ्यांनुसार (नोव्हेंबर २०२५) अंदाजित ९०,०००+ भटक्या श्वानांविरुद्ध BMC केवळ {0} ABC केंद्रे चालवते. १९९४ ते डिसेंबर २०२३ दरम्यान ४,०३,३७४ श्वानांचे निर्बीजीकरण झाले असून, वार्षिक ४५,००० चे उद्दिष्ट आणि सध्याच्या मोहिमेसाठी ₹२३ कोटींची तरतूद आहे.',
  'For context: BMC registered {0} deaths in {1} (provisional) and {2} births in {3} - the lowest annual birth count since 2015, a 23% drop on 2019. These are annual totals, not directly comparable to the rolling 30-day figure above.':
    'संदर्भासाठी: BMC ने {1} मध्ये {0} मृत्यू (प्रारूप) आणि {3} मध्ये {2} जन्म नोंदवले - २०१५ नंतरची सर्वात कमी वार्षिक जन्म संख्या, २०१९ च्या तुलनेत २३% घट. हे वार्षिक एकूण आकडे आहेत, वरील फिरत्या ३०-दिवसांच्या आकड्याशी थेट तुलनीय नाहीत.',
  "For context: ~{0} complaints were logged via BMC's Central Complaint Registration System in 2024, a 70% increase since 2015, per Praja Foundation's RTI-based report (May 2025). That figure covers only water, waste, sewage, pollution and toilets - not every complaint category modelled on this page.":
    'संदर्भासाठी: प्रजा फाउंडेशनच्या माहिती अधिकार-आधारित अहवालानुसार (मे २०२५) २०२४ मध्ये BMC च्या केंद्रीय तक्रार नोंदणी प्रणालीद्वारे सुमारे {0} तक्रारी नोंदवल्या गेल्या, २०१५ पासून ७०% वाढ. हा आकडा केवळ पाणी, कचरा, मलनि:सारण, प्रदूषण आणि शौचालये यांपुरता मर्यादित आहे - या पानावर प्रतिकृत केलेल्या प्रत्येक तक्रार प्रवर्गासाठी नव्हे.',
  'For context: the "Mumbai Speaks" survey (Mumbai Citizens\' Forum with TISS; 5,450 respondents across all 227 wards, published Dec 2025) found {0}% of citizens unaware their ward even has a statutory Ward Committee - while {1}% want greater involvement in local decision-making. Awareness of the participation channel, not appetite for it, is the gap this register measures against.':
    'संदर्भासाठी: "मुंबई स्पीक्स" सर्वेक्षणात (मुंबई सिटिझन्स फोरम व TISS; सर्व २२७ प्रभागांतील ५,४५० प्रतिसादकर्ते, डिसेंबर २०२५ प्रकाशित) असे आढळले की {0}% नागरिकांना त्यांच्या प्रभागात वैधानिक वॉर्ड कमिटी आहे हेच माहीत नाही - तर {1}% ला स्थानिक निर्णय-प्रक्रियेत अधिक सहभाग हवा आहे. सहभाग माध्यमाबाबतची जागरूकता, त्यासाठीची इच्छा नव्हे, ही हे नोंदवही मोजत असलेली तफावत आहे.',
  "For context: a 2025 academic study puts Mumbai's actual shoreline at ~{0} km - no official BMC or state figure for total coastline length was found.":
    'संदर्भासाठी: २०२५ च्या शैक्षणिक अभ्यासानुसार मुंबईची प्रत्यक्ष किनारपट्टी सुमारे {0} कि.मी. आहे - एकूण किनारपट्टी लांबीसाठी कोणताही अधिकृत BMC किंवा राज्य आकडा आढळला नाही.',
  "For context: the India State of Forest Report puts Mumbai's mangrove cover at ~{0} sq km ({1} ha), against a materially higher 65 sq km academic estimate with no stated measurement date - a genuine disagreement between a government forest survey and an academic study, not reconciled here.":
    'संदर्भासाठी: भारतीय वन सर्वेक्षण अहवालानुसार मुंबईचे कांदळवन आच्छादन सुमारे {0} चौ.कि.मी. ({1} हेक्टर) आहे, तर एका शैक्षणिक अंदाजानुसार ते लक्षणीयरीत्या जास्त, ६५ चौ.कि.मी. आहे, ज्यासाठी कोणतीही मोजणी तारीख नमूद नाही - सरकारी वन सर्वेक्षण आणि शैक्षणिक अभ्यास यांच्यातील हा खरा मतभेद येथे समेट केलेला नाही.',
  'For context: contemporary reporting counts {0} Hindu Shamshan-bhoomi (cremation grounds) citywide, separately from 10 electric and 18 gas crematoria as a technology category within that estate. No single official citywide inventory document was found.':
    'संदर्भासाठी: समकालीन वृत्तांकनानुसार शहरभर {0} हिंदू स्मशानभूमी आहेत, त्या मालमत्तेतील एक तंत्रज्ञान प्रवर्ग म्हणून असलेल्या १० विद्युत आणि १८ गॅस स्मशानांव्यतिरिक्त. एकच अधिकृत शहरव्यापी सूची दस्तऐवज आढळला नाही.',
  "Named repeatedly across years of BMC monsoon reporting as the city's chronic waterlogging spots — a standing, publicly documented list, distinct from the incident register's live operational entries at left.":
    'BMC च्या अनेक वर्षांच्या पावसाळी वृत्तांकनात शहरातील दीर्घकालीन पाणी साचण्याची ठिकाणे म्हणून वारंवार नमूद - ही एक स्थायी, सार्वजनिकरीत्या दस्तऐवजीकृत यादी आहे, डावीकडील घटना नोंदवहीतील थेट कार्यान्वयन नोंदींपेक्षा वेगळी.',
  'For context: BMC\'s official register lists {0} Recreation Ground / Playground / Garden plots citywide ({1} of them gardens specifically). Its 2018 tree census counted {2} trees, up from ~19 lakh in 2008; the next census is ground-penetrating-radar based.':
    'संदर्भासाठी: BMC च्या अधिकृत नोंदवहीत शहरभर {0} करमणूक मैदान/खेळाचे मैदान/बाग भूखंड नोंदवलेले आहेत ({1} विशेषतः बागा आहेत). त्याच्या २०१८ च्या वृक्ष गणनेत {2} झाडे मोजली गेली, २००८ मधील सुमारे १९ लाखांवरून वाढ; पुढील गणना भू-भेदी रडार आधारित असेल.',
  "For context: a compilation of BMC's own ward-by-ward heritage lists counts {0} graded structures plus {1} precincts citywide (Grade I: 51, IIA: 282, IIB: 289, III: 606). No single official MCGM document giving this aggregate total was found.":
    'संदर्भासाठी: BMC च्या स्वतःच्या प्रभागनिहाय वारसा याद्यांच्या संकलनानुसार शहरभर {0} श्रेणीबद्ध वास्तू व {1} परिक्षेत्रे आहेत (श्रेणी I: ५१, IIA: २८२, IIB: २८९, III: ६०६). हा एकत्रित एकूण आकडा देणारा एकच अधिकृत MCGM दस्तऐवज आढळला नाही.',
  "For context: BMC's own facility network runs {0} specialised major hospitals (including four medical colleges), {1} health posts, {2} dispensaries and {3} maternity homes.":
    'संदर्भासाठी: BMC चे स्वतःचे सुविधा जाळे {0} विशेषोपचार प्रमुख रुग्णालये (चार वैद्यकीय महाविद्यालयांसह), {1} आरोग्य केंद्रे, {2} दवाखाने आणि {3} प्रसूतिगृहे चालवते.',
  'For context: ~{0}% of Mumbai\'s population lived in slum areas per Census of India 2011 provisional data, widely repeated in secondary reporting - the primary Census "Primary Census Abstract for Slums" table itself could not be located directly.':
    'संदर्भासाठी: भारताच्या जनगणना २०११ च्या प्रारूप आकडेवारीनुसार मुंबईच्या सुमारे {0}% लोकसंख्या झोपडपट्टी भागांत राहत होती, हे दुय्यम वृत्तांकनात मोठ्या प्रमाणात पुनरावृत्त झाले आहे - मूळ जनगणनेची "झोपडपट्ट्यांसाठी प्राथमिक जनगणना सारांश" सारणी स्वतः थेट सापडली नाही.',
  'For context: BMC operates {0} municipal markets citywide (2019 reporting put 92 of them in dilapidated condition); a separate 2022 count found 92 vegetable markets with 17,164 licensed vendors. No more recent citywide recount was found.':
    'संदर्भासाठी: BMC शहरभर {0} महानगरपालिका बाजार चालवते (२०१९ च्या वृत्तांकनानुसार त्यांपैकी ९२ जीर्ण अवस्थेत होते); एका स्वतंत्र २०२२ च्या गणनेत ९२ भाजी बाजार व १७,१६४ परवानाधारक विक्रेते आढळले. त्यानंतरची अधिक अलीकडील शहरव्यापी पुनर्गणना आढळली नाही.',
  "For context: BMC's own network runs {0} specialised major hospitals, {1} health posts, {2} dispensaries and {3} maternity homes.":
    'संदर्भासाठी: BMC चे स्वतःचे जाळे {0} विशेषोपचार प्रमुख रुग्णालये, {1} आरोग्य केंद्रे, {2} दवाखाने आणि {3} प्रसूतिगृहे चालवते.',
  'For context: BMC\'s own published road network is ~{0} km citywide. Its "Pedestrians First" enforcement drive separately cleared {1} km of encroached footpaths in 2025-26.':
    'संदर्भासाठी: BMC चे स्वतःचे प्रकाशित रस्ता जाळे शहरभर सुमारे {0} कि.मी. आहे. त्याच्या "पादचारी प्रथम" अंमलबजावणी मोहिमेने २०२५-२६ मध्ये स्वतंत्रपणे {1} कि.मी. अतिक्रमित पदपथ मोकळे केले.',
  "For context: BMC's eight existing STPs run ~{0} MLD combined dry-weather capacity today, most providing preliminary rather than full secondary treatment. Seven more plants totalling 2,464 MLD are under construction under MSDP-II.":
    'संदर्भासाठी: BMC चे सध्याचे आठ मलनि:सारण प्रक्रिया प्रकल्प आज एकत्रितपणे सुमारे {0} MLD कोरड्या-हवामान क्षमतेने चालतात, बहुतांश पूर्ण द्वितीयक प्रक्रियेऐवजी केवळ प्राथमिक प्रक्रिया देतात. MSDP-II अंतर्गत एकूण २,४६४ MLD चे आणखी सात प्रकल्प बांधकामाधीन आहेत.',
  "For context: BMC's own reporting puts the city at ~{0} tonnes of waste per day (2025, Deonar dumping ground closure plan). Other 2024-25 reports range 6,200-7,200 TPD; older 8,000-9,800 TPD figures included construction and demolition debris.":
    'संदर्भासाठी: BMC च्या स्वतःच्या वृत्तांकनानुसार शहरात दररोज सुमारे {0} टन कचरा तयार होतो (२०२५, देवनार क्षेपणभूमी बंद करण्याची योजना). इतर २०२४-२५ च्या अहवालांनुसार ही श्रेणी ६,२००-७,२०० TPD आहे; जुने ८,०००-९,८०० TPD आकडे बांधकाम व पाडकाम मलब्यासह होते.',
  'For context: under BRIMSTOWAD, the post-2005-flood drainage upgrade programme, {0} of {1} Chitale-Committee-recommended pumping stations are built and operational; the remaining two (Mogra, Mahul) are still delayed by land/CRZ clearance. Programme cost has escalated to ~₹{2} crore.':
    'संदर्भासाठी: BRIMSTOWAD या २००५ नंतरच्या पूर-नि:सारण श्रेणीवर्धन कार्यक्रमांतर्गत, चितळे समितीने शिफारस केलेल्या {1} पैकी {0} उपसा केंद्रे बांधून कार्यरत आहेत; उर्वरित दोन (मोग्रा, माहुल) अद्याप जमीन/CRZ मंजुरीमुळे विलंबित आहेत. कार्यक्रमाचा खर्च वाढून सुमारे ₹{2} कोटी झाला आहे.',
  "For context: BMC's own LED-conversion project converted {0} streetlights across the western and eastern suburbs, ~97% of that project complete (30 Jan 2023). This is the suburban conversion count only - no citywide total streetlight figure (including the island city) was found.":
    'संदर्भासाठी: BMC च्या स्वतःच्या LED-रूपांतरण प्रकल्पाने पश्चिम व पूर्व उपनगरांतील {0} पथदिवे रूपांतरित केले, त्या प्रकल्पाचे सुमारे ९७% काम पूर्ण (३० जानेवारी २०२३). ही केवळ उपनगरीय रूपांतरण संख्या आहे - शहरव्यापी (बेट शहरासह) एकूण पथदिवे आकडा आढळला नाही.',
  "For context: BMC's own Environment Status Report counts {0} registered vehicles citywide as of March {1} — ~2.94 lakh new registrations that year, +6.2% on the year before.":
    'संदर्भासाठी: BMC च्या स्वतःच्या पर्यावरण स्थिती अहवालानुसार मार्च {1} पर्यंत शहरभर {0} नोंदणीकृत वाहने — त्या वर्षी सुमारे २.९४ लाख नवीन नोंदणी, मागील वर्षाच्या तुलनेत +६.२%.',
  "For context: Mumbai Traffic Police's official road-safety report recorded {0} road-accident fatalities citywide in {1} — a ~39-40% reduction versus 2015. Two/three-wheeler occupants and pedestrians are the largest victim categories.":
    'संदर्भासाठी: मुंबई वाहतूक पोलिसांच्या अधिकृत रस्ता-सुरक्षा अहवालानुसार {1} मध्ये शहरभर {0} रस्ता-अपघात मृत्यू नोंदवले गेले — २०१५ च्या तुलनेत सुमारे ३९-४०% घट. दुचाकी/तीनचाकी वाहनांवरील व्यक्ती आणि पादचारी हे सर्वाधिक बळींचे प्रवर्ग आहेत.',
  "For context: BMC's own published bulk supply is {0} MLD against a demand of ~4,300 MLD, drawn from seven lakes — Bhatsa, Upper Vaitarna, Middle Vaitarna, Modak Sagar, Tansa, Vihar and Tulsi. That is a citywide bulk figure, not a sum of the zone rows below.":
    'संदर्भासाठी: BMC चा स्वतःचा प्रकाशित मोठ्या प्रमाणातील पुरवठा सुमारे ४,३०० MLD मागणीविरुद्ध {0} MLD आहे, सात तलावांमधून घेतला जातो — भातसा, अप्पर वैतरणा, मिडल वैतरणा, मोडक सागर, तानसा, विहार आणि तुळशी. हा शहरव्यापी मोठ्या प्रमाणातील आकडा आहे, खालील क्षेत्रीय ओळींची बेरीज नव्हे.',
  'Replay briefing': 'माहितीपर सत्र पुन्हा पाहा',
  "For context: BMC's own {0} budget outlay is {1}, presented 25 Feb 2026 by the Commissioner - up 8.77% on {2}'s ₹74,427.41 crore, and India's largest municipal budget. This total includes capital spend and borrowings, distinct from the revenue-income estimate elsewhere on this platform.":
    'संदर्भासाठी: BMC चा स्वतःचा {0} अर्थसंकल्पीय खर्च {1} आहे, आयुक्तांनी २५ फेब्रुवारी २०२६ रोजी सादर केला - {2} च्या ₹७४,४२७.४१ कोटींपेक्षा ८.७७% वाढ, आणि भारतातील सर्वात मोठा महानगरपालिका अर्थसंकल्प. या एकूण रकमेत भांडवली खर्च व कर्जे समाविष्ट आहेत, या मंचावरील इतरत्र दिलेल्या महसूल-उत्पन्न अंदाजापेक्षा वेगळे.',
  'For context: BMC\'s {0} pre-monsoon list flagged {1} "most dangerous" C1 buildings citywide (23 MCGM-owned + 141 private + 10 government/MHADA-owned). This count fluctuates year to year rather than trending in one direction - 2024 was 188, 2025 was 134.':
    'संदर्भासाठी: BMC च्या {0} च्या पावसाळापूर्व यादीत शहरभर {1} "सर्वाधिक धोकादायक" C1 इमारती चिन्हांकित (२३ MCGM-मालकीच्या + १४१ खासगी + १० सरकारी/म्हाडा-मालकीच्या). ही संख्या एका दिशेने कल दाखवण्याऐवजी दरवर्षी चढ-उतार दाखवते - २०२४ मध्ये १८८ होती, २०२५ मध्ये १३४.',
  'For context: BMC\'s "Pedestrians First" campaign (2025-26, ongoing) cleared {0} km of encroached footpaths across 443 total enforcement actions - the best-available city-level encroachment-removal reference found; no single official annual aggregate is published citywide, only ward-level and campaign-level figures like this one.':
    'संदर्भासाठी: BMC च्या "पादचारी प्रथम" मोहिमेने (२०२५-२६, सुरू असलेली) एकूण ४४३ अंमलबजावणी कारवायांमधून {0} कि.मी. अतिक्रमित पदपथ मोकळे केले - शहरस्तरीय अतिक्रमण-निष्कासनाचा हा सर्वोत्तम उपलब्ध संदर्भ आहे; शहरभर एकच अधिकृत वार्षिक एकत्रित आकडेवारी प्रकाशित होत नाही, केवळ या सारखे प्रभागस्तरीय व मोहीमस्तरीय आकडे.',
  'For context: three real agency-led works anchor this register - the Coastal Road (Phase 1, {0} km, opened {1}, ~₹{2} crore, "the most expensive project in BMC\'s history"), the Goregaon-Mulund Link Road (₹{3} crore, {4} km twin tunnel beneath SGNP), and the Gargai Dam (₹{5} crore, {6} MLD additional yield, still pre-construction).':
    'संदर्भासाठी: तीन प्रत्यक्ष संस्था-नेतृत्वाखालील कामे या नोंदवहीचा आधार आहेत - कोस्टल रोड (फेज १, {0} कि.मी., {1} रोजी खुला, सुमारे ₹{2} कोटी, "BMC च्या इतिहासातील सर्वाधिक खर्चिक प्रकल्प"), गोरेगाव-मुलुंड लिंक रोड (₹{3} कोटी, SGNP खालील {4} कि.मी.ची जुळी बोगदा), आणि गारगाई धरण (₹{5} कोटी, अतिरिक्त {6} MLD उत्पन्न, अद्याप बांधकामपूर्व टप्प्यात).',
}
