/** Marathi catalogue, part 37. Keyed by the exact English source.
 * CockpitBriefing.tsx, corporations.ts citation notes and navigation.ts descriptions. */
export const MR_PART_37: Record<string, string> = {
  "Today's briefing · Step {0} of {1}": 'आजचे माहितीपर सत्र · टप्पा {0} पैकी {1}',

  '₹13,060 crore for the completed 10.58 km Phase 1 (Marine Drive–Worli) south leg — escalated from an original ₹12,721 crore estimate, "the most expensive project in BMC\'s history." The full 29.2 km project (Phase 1 + 2) is more honestly a ₹13,000–14,000 crore range across sources. The separate Versova–Dahisar–Bhayander "Coastal Road North" extension (~₹16,600–22,000 crore, still in early clearance) is a distinct project not included in this figure.':
    'पूर्ण झालेल्या १०.५८ कि.मी.च्या फेज १ (मरीन ड्राइव्ह-वरळी) दक्षिण टप्प्यासाठी ₹१३,०६० कोटी — मूळ ₹१२,७२१ कोटींच्या अंदाजापेक्षा वाढून, "BMC च्या इतिहासातील सर्वाधिक खर्चिक प्रकल्प." संपूर्ण २९.२ कि.मी.चा प्रकल्प (फेज १ + २) विविध स्रोतांनुसार अधिक प्रामाणिकपणे ₹१३,०००-१४,००० कोटींच्या श्रेणीत आहे. स्वतंत्र वर्सोवा-दहिसर-भाईंदर "कोस्टल रोड नॉर्थ" विस्तार (~₹१६,६००-२२,००० कोटी, अद्याप प्राथमिक मंजुरी टप्प्यात) हा वेगळा प्रकल्प असून तो या आकड्यात समाविष्ट नाही.',
  "Phase 1 southbound (Marine Lines–Worli) opened 11 March 2024; the northbound bridge to the Bandra–Worli Sea Link was inaugurated 26 January 2025. Phase 2 (Worli/Bandra–Versova/Kandivali, 19.22 km) is under construction; BMC's stated full-completion target is May 2026 (a target, not a confirmed deadline — this project has slipped before).":
    'फेज १ दक्षिणवाहिनी (मरीन लाइन्स-वरळी) ११ मार्च २०२४ रोजी खुली झाली; वांद्रे-वरळी सी लिंकला जोडणारा उत्तरवाहिनी पूल २६ जानेवारी २०२५ रोजी उद्घाटित झाला. फेज २ (वरळी/वांद्रे-वर्सोवा/कांदिवली, १९.२२ कि.मी.) बांधकामाधीन आहे; BMC चे नमूद पूर्ण-समाप्तीचे लक्ष्य मे २०२६ आहे (हे एक लक्ष्य आहे, निश्चित अंतिम मुदत नव्हे — या प्रकल्पाला याआधीही विलंब झाला आहे).',
  'Escalated to ~₹4,000 crore against an original 2005-era estimate of ₹1,200 crore — a 3x+ overrun over roughly 11 years. This is the last-published aggregate figure found (2017); no more recent total cost was located.':
    '२००५ सालच्या मूळ ₹१,२०० कोटींच्या अंदाजाच्या तुलनेत वाढून सुमारे ₹४,००० कोटी झाले — सुमारे ११ वर्षांत ३ पटींहून अधिक वाढ. हा शेवटचा प्रकाशित एकत्रित आकडा आहे (२०१७); त्यानंतरचा अधिक अलीकडील एकूण खर्च आढळला नाही.',
  "6 of 8 Chitale-Committee-recommended pumping stations completed and operational (Irla, Haji Ali, Love Grove, Cleveland Bunder, Britannia, Gazdar Bandh); the remaining two, Mogra and Mahul, are still not completed as of 2025, delayed by land/CRZ clearance — Mogra's site was found to overlap with the Coastal Road North alignment, requiring re-siting.":
    'चितळे समितीने शिफारस केलेल्या ८ पैकी ६ उपसा केंद्रे पूर्ण होऊन कार्यरत आहेत (इर्ला, हाजी अली, लव्ह ग्रोव्ह, क्लीव्हलँड बंदर, ब्रिटानिया, गझदर बंद); उर्वरित दोन, मोग्रा आणि माहुल, २०२५ पर्यंत अद्याप पूर्ण झालेली नाहीत, जमीन/CRZ मंजुरीमुळे विलंब; मोग्राची जागा कोस्टल रोड नॉर्थच्या मार्गिकेशी आच्छादित आढळल्याने पुनर्स्थान आवश्यक आहे.',
  '174 C1-category ("most dangerous") buildings flagged in BMC\'s 2026 pre-monsoon list (23 MCGM-owned + 141 private + 10 government/MHADA-owned), released ~29 April 2026; 72 had been vacated by report date. This count fluctuates year to year rather than trending in one direction — 2024\'s list was 188, 2025\'s was 134 — so it should not be treated as a stable baseline.':
    'BMC च्या २०२६ च्या पावसाळापूर्व यादीत १७४ C1-श्रेणीच्या ("सर्वाधिक धोकादायक") इमारती चिन्हांकित (२३ MCGM-मालकीच्या + १४१ खासगी + १० सरकारी/म्हाडा-मालकीच्या), सुमारे २९ एप्रिल २०२६ रोजी प्रसिद्ध; अहवाल तारखेपर्यंत ७२ रिकाम्या करण्यात आल्या होत्या. ही संख्या एका दिशेने कल दाखवण्याऐवजी दरवर्षी चढ-उतार दाखवते — २०२४ ची यादी १८८ होती, २०२५ ची १३४ — त्यामुळे ही स्थिर आधाररेषा मानू नये.',
  "Most commonly cited total project cost is ₹14,000 crore, with the underground twin-tunnel component separately bid at ₹6,300–6,600 crore; one source gives a lower all-in total of ₹12,013 crore. Reported here as a ₹12,000–14,000 crore range given genuine disagreement across sources. Phase 1 flyover targeted to open May 2026; BMC's stated full-corridor completion target is 2028.":
    'सर्वाधिक उद्धृत एकूण प्रकल्प खर्च ₹१४,००० कोटी असून, भूमिगत जुळ्या-बोगद्याचा घटक स्वतंत्रपणे ₹६,३००-६,६०० कोटींना निविदाबद्ध आहे; एका स्रोतानुसार सर्वसमावेशक एकूण खर्च कमी, ₹१२,०१३ कोटी आहे. स्रोतांमध्ये खरा मतभेद असल्याने येथे ₹१२,०००-१४,००० कोटींची श्रेणी नोंदवली आहे. फेज १ उड्डाणपूल मे २०२६ मध्ये खुला करण्याचे लक्ष्य; BMC चे संपूर्ण मार्गिका पूर्णत्वाचे नमूद लक्ष्य २०२८ आहे.',
  '6.65 km twin-tunnel system beneath Sanjay Gandhi National Park, depth 20–160 m; tunnel-boring machine imported from Japan, boring targeted to start early 2026.':
    'संजय गांधी राष्ट्रीय उद्यानाखालील ६.६५ कि.मी.ची जुळी-बोगदा प्रणाली, खोली २०-१६० मी.; जपानहून आयात केलेले बोगदा-खनन यंत्र, खनन कार्य २०२६ च्या सुरुवातीस सुरू करण्याचे लक्ष्य.',
  "₹5,396 crore sanctioned/proposed project estimate; a separate ₹3,000 crore construction tender was issued December 2025 — these are not directly comparable (full project cost vs. one construction tender) so both figures exist without being merged. Dam: 69 m height, 979.4 m length, on the Gargai River near Ogde village, Wada taluka, Palghar district, linked to Modak Sagar via a 1.6 km tunnel. BMC's stated completion target is 2029, a project with over a decade of prior delay pending clearances.":
    'रु.५,३९६ कोटींचा मंजूर/प्रस्तावित प्रकल्प अंदाज; डिसेंबर २०२५ मध्ये स्वतंत्र ₹३,००० कोटींची बांधकाम निविदा जारी — हे दोन्ही थेट तुलनीय नाहीत (संपूर्ण प्रकल्प खर्च वि. एक बांधकाम निविदा) त्यामुळे दोन्ही आकडे एकत्र न करता नमूद केले आहेत. धरण: उंची ६९ मी., लांबी ९७९.४ मी., पालघर जिल्ह्यातील वाडा तालुक्यातील ओगदे गावाजवळ गारगाई नदीवर, १.६ कि.मी.च्या बोगद्याद्वारे मोडक सागरशी जोडलेले. BMC चे नमूद पूर्णत्वाचे लक्ष्य २०२९ असून, या प्रकल्पाला मंजुरीच्या प्रतीक्षेत दशकाहूनही अधिक काळ आधीच विलंब झाला आहे.',
  '440 MLD additional yield once complete — one of three planned new sources (with Pinjal Dam and the Damanganga–Pinjal link) collectively targeted to add 2,891 MLD. Pinjal Dam has no independently citable standalone cost/status figure and is not carried as a separate field.':
    'पूर्ण झाल्यावर अतिरिक्त ४४० MLD उत्पन्न — पिंजाळ धरण आणि दमणगंगा-पिंजाळ जोडणीसह नियोजित तीन नव्या स्रोतांपैकी एक, जे एकत्रितपणे २,८९१ MLD जोडण्याचे लक्ष्य ठेवतात. पिंजाळ धरणासाठी स्वतंत्रपणे उद्धृत करण्यायोग्य स्वतंत्र खर्च/स्थिती आकडा उपलब्ध नाही, त्यामुळे तो वेगळे क्षेत्र म्हणून नोंदवलेला नाही.',
  'BMC\'s own Environment Status Report 2024-25: 50,54,907 registered vehicles as of March 2025, up from 47,59,976 (2024) and 45,37,211 (2023); ~2.94 lakh new registrations in the year (+6.2%). Two-wheelers 59.34%, cars/jeeps/station wagons 28.72%; by fuel, petrol 78.79%, diesel 11.15%, CNG 4.36 lakh, electric just 48,854.':
    'BMC च्या स्वतःच्या पर्यावरण स्थिती अहवाल २०२४-२५ नुसार: मार्च २०२५ पर्यंत ५०,५४,९०७ नोंदणीकृत वाहने, २०२४ मधील ४७,५९,९७६ आणि २०२३ मधील ४५,३७,२११ वरून वाढ; वर्षभरात सुमारे २.९४ लाख नवीन नोंदणी (+६.२%). दुचाकी ५९.३४%, कार/जीप/स्टेशन वॅगन २८.७२%; इंधननिहाय, पेट्रोल ७८.७९%, डिझेल ११.१५%, CNG ४.३६ लाख, विद्युत केवळ ४८,८५४.',
  "374 deaths in 351 crashes (2023), per Mumbai Traffic Police's official annual road-safety report with the Bloomberg Philanthropies Initiative for Global Road Safety (BIGRS) — a ~39-40% reduction versus 2015; 2022 was 365 deaths in 351 crashes. Two/three-wheeler occupants (48-49%) and pedestrians (~40%) are the largest victim categories; hit-and-run caused 38% of fatal crashes. A separately-reported 2024 figure of 1,108 deaths is attributed to a private company, not Mumbai Traffic Police, and could not be corroborated — not used here.":
    'मुंबई वाहतूक पोलिसांच्या ब्लूमबर्ग फिलान्थ्रॉपीज इनिशिएटिव्ह फॉर ग्लोबल रोड सेफ्टी (BIGRS) सह अधिकृत वार्षिक रस्ता-सुरक्षा अहवालानुसार ३५१ अपघातांत ३७४ मृत्यू (२०२३) — २०१५ च्या तुलनेत सुमारे ३९-४०% घट; २०२२ मध्ये ३५१ अपघातांत ३६५ मृत्यू होते. दुचाकी/तीनचाकी वाहनांवरील व्यक्ती (४८-४९%) आणि पादचारी (सुमारे ४०%) हे सर्वाधिक बळींचे प्रवर्ग आहेत; अपघातानंतर पळून जाण्यामुळे ३८% प्राणघातक अपघात झाले. स्वतंत्रपणे नोंदवलेला २०२४ चा १,१०८ मृत्यूंचा आकडा एका खासगी कंपनीचा असून, मुंबई वाहतूक पोलिसांचा नव्हे, आणि त्याची पुष्टी होऊ शकली नाही — तो येथे वापरलेला नाही.',
  '68 km of footpaths cleared and 443 total enforcement actions under BMC\'s "Pedestrians First" campaign (2025-26, ongoing) — the best-available city-level encroachment-removal reference found; BMC does not appear to publish a single official annual aggregate for structures removed or area reclaimed citywide, only ward-level and campaign-level figures like this one.':
    'BMC च्या "पादचारी प्रथम" मोहिमेअंतर्गत (२०२५-२६, सुरू असलेली) ६८ कि.मी. पदपथ मोकळे केले आणि एकूण ४४३ अंमलबजावणी कारवाया — शहरस्तरीय अतिक्रमण-निष्कासनाचा हा सर्वोत्तम उपलब्ध संदर्भ आहे; BMC शहरव्यापी काढून टाकलेल्या संरचना किंवा मोकळ्या केलेल्या क्षेत्राची एकच अधिकृत वार्षिक एकत्रित आकडेवारी प्रकाशित करताना दिसत नाही, केवळ या सारखे प्रभागस्तरीय व मोहीमस्तरीय आकडे.',
  '52 Hindu Shamshan-bhoomi (cremation grounds) citywide (June 2024 reporting); BMC separately runs 10 electric and 18 gas crematoria as a technology category within that estate, and piloted an eco-friendly enclosed-furnace system at 10 locations from 2020, each handling ~10-12 funerals a day. No official single citywide inventory document was found; this is the best-available count from contemporary reporting.':
    'शहरभर ५२ हिंदू स्मशानभूमी (जून २०२४ वृत्तांकन); BMC त्या मालमत्तेतील एक तंत्रज्ञान प्रवर्ग म्हणून स्वतंत्रपणे १० विद्युत आणि १८ गॅस स्मशाने चालवते, आणि २०२० पासून १० ठिकाणी पर्यावरणस्नेही बंदिस्त-भट्टी प्रणालीचा प्रायोगिक वापर केला, प्रत्येकी दररोज सुमारे १०-१२ अंत्यसंस्कार हाताळत. एकच अधिकृत शहरव्यापी सूची दस्तऐवज आढळला नाही; हा समकालीन वृत्तांकनातील सर्वोत्तम उपलब्ध आकडा आहे.',
  '150 km of shoreline, per a 2025 academic study evaluating a decade of Mumbai mangrove restorations (Columbia University Consilience journal) — no official BMC or state figure was found for total coastline length.':
    'मुंबईतील दशकभराच्या कांदळवन पुनर्स्थापनेचे मूल्यमापन करणाऱ्या २०२५ च्या शैक्षणिक अभ्यासानुसार (कोलंबिया विद्यापीठाचे Consilience जर्नल) १५० कि.मी. किनारपट्टी — एकूण किनारपट्टी लांबीसाठी कोणताही अधिकृत BMC किंवा राज्य आकडा आढळला नाही.',
  '40 sq km of mangrove cover in Mumbai city, per the India State of Forest Report (Forest Survey of India), which also recorded 1.08 sq km lost — the highest loss of any area measured. A separate 2025 academic study (Columbia University Consilience journal) gives a materially higher estimate of 65 sq km with no stated measurement date; reported here as a genuine disagreement between a government forest survey and an academic estimate, not reconciled.':
    'भारतीय वन सर्वेक्षण अहवालानुसार (Forest Survey of India) मुंबई शहरात ४० चौ.कि.मी. कांदळवन आच्छादन, ज्यात १.०८ चौ.कि.मी. नुकसान नोंदवले गेले — मोजलेल्या कोणत्याही क्षेत्रातील सर्वाधिक नुकसान. एका स्वतंत्र २०२५ च्या शैक्षणिक अभ्यासाने (कोलंबिया विद्यापीठाचे Consilience जर्नल) ६५ चौ.कि.मी.चा लक्षणीयरीत्या जास्त अंदाज दिला असून त्यासाठी कोणतीही मोजणी तारीख नमूद नाही; हा सरकारी वन सर्वेक्षण आणि शैक्षणिक अंदाज यांच्यातील खरा मतभेद म्हणून येथे नोंदवला आहे, समेट केलेला नाही.',
  "\"Mumbai Speaks\" survey by Mumbai Citizens' Forum with TISS (fieldwork Jan-Aug 2023, published 24 Dec 2025): 5,450 respondents across all 227 wards, 70% unaware their ward has a Prabhag Samiti / Ward Committee, 72% do not know BMC's budget, 75% unaware of the Local Area Development Fund, 35% do not know how to contact their corporator.":
    'मुंबई सिटिझन्स फोरम आणि TISS यांचे "मुंबई स्पीक्स" सर्वेक्षण (क्षेत्रकार्य जाने-ऑगस्ट २०२३, प्रकाशित २४ डिसेंबर २०२५): सर्व २२७ प्रभागांतील ५,४५० प्रतिसादकर्ते, ७०% ला त्यांच्या प्रभागात प्रभाग समिती / वॉर्ड कमिटी आहे हे माहीत नाही, ७२% ला BMC चा अर्थसंकल्प माहीत नाही, ७५% ला स्थानिक क्षेत्र विकास निधीबद्दल माहिती नाही, ३५% ला त्यांच्या नगरसेवकाशी संपर्क कसा साधावा हे माहीत नाही.',
  'Same "Mumbai Speaks" survey: 88.7% of respondents want greater involvement in local decision-making; 47.6% had attempted resolving a local issue themselves, of whom only 57.4% reported success; 72.5% intended to vote in the upcoming BMC election. Area Sabha, Ward Committees, social media and citizen forums were the preferred participation channels.':
    'तेच "मुंबई स्पीक्स" सर्वेक्षण: ८८.७% प्रतिसादकर्त्यांना स्थानिक निर्णय-प्रक्रियेत अधिक सहभाग हवा आहे; ४७.६% नी स्वतः स्थानिक समस्या सोडवण्याचा प्रयत्न केला, त्यापैकी केवळ ५७.४% यशस्वी झाल्याचे नोंदवले; ७२.५% आगामी BMC निवडणुकीत मतदान करण्याचा मानस बाळगून होते. क्षेत्र सभा, वॉर्ड कमिट्या, समाजमाध्यमे आणि नागरिक मंच हे पसंतीचे सहभाग माध्यम होते.',

  'One live, spatial view of incidents, at-risk projects and road defects across every ward.':
    'प्रत्येक प्रभागातील घटना, जोखीमग्रस्त प्रकल्प आणि रस्ता दोष यांचे एक थेट, स्थानिक दृश्य.',
  'Every statutory certificate, licence and permit measured against its published turnaround, across every department.':
    'प्रत्येक विभागातील प्रत्येक वैधानिक प्रमाणपत्र, परवाना आणि अनुमती यांचे त्यांच्या प्रकाशित कालमर्यादेविरुद्ध मापन.',
  'Data & Resources': 'माहिती व संसाधने',
  "The citation register behind this platform's factual spine - every published figure, and exactly where it was read.":
    'या मंचाच्या तथ्यात्मक कण्यामागील उद्धरण नोंदवही - प्रत्येक प्रकाशित आकडा, आणि तो नेमका कुठे वाचला गेला.',
  'Testing & Quality Assurance': 'चाचणी व गुणवत्ता हमी',
  'What has actually been verified against this build, how, and what has not - stated plainly.':
    'या बांधणीविरुद्ध प्रत्यक्षात काय पडताळले गेले, कसे, आणि काय पडताळले गेले नाही - स्पष्टपणे नमूद.',
  'Upload a real property-tax CSV export and see it rendered - the one connector in this platform that is not demonstration data.':
    'प्रत्यक्ष मालमत्ता-कर CSV निर्यात फाइल अपलोड करा आणि ती सादर होताना पाहा - या मंचावरील प्रात्यक्षिक माहिती नसलेला हा एकमेव जोडणी बिंदू आहे.',
}
